CREATE TABLE SINISTRO (
    SINISTRO_ID INT IDENTITY(1,1)
    , REFERENCIA INT
    , DATA_OCORRENCIA SMALLDATETIME
    , SEGURADO_ID INT
    , BILHETE VARCHAR(10)
    , VOUCHER VARCHAR(20)
    , TIPO_COBERTURA_ID INT
    , DATA_CRIACAO SMALLDATETIME DEFAULT GETDATE()
    , NOTA_DEBITO_ID INT
);
GO

CREATE TABLE REEMBOLSO (
    REEMBOLSO_ID INT IDENTITY(1,1)
    , REF_RELACAO SMALLDATETIME
    , COMPANHIA_ID INT
    , SEGURADORA_ID INT
    , PRAZO_PAGAMENTO SMALLDATETIME
    , SINISTRO_ID INT
    , VALOR_DOLAR MONEY
    , VALOR_REAL MONEY
    , TRANSFERENCIA_CONTA BIT
    , EMAIL_PAX VARCHAR(100)
    , CADASTRO_CONTA BIT
    , DATA_PAGAMENTO SMALLDATETIME
    , DOC_DEVOLVIDO BIT
    , OBSERVACAO VARCHAR(4000)
    , DATA_RECEBIMENTO SMALLDATETIME
    , DATA_CRIACAO SMALLDATETIME DEFAULT GETDATE()
);
GO

CREATE TABLE COMPANHIA (
    COMPANHIA_ID INT IDENTITY(1,1)
    , NOME VARCHAR(100)
    , CNPJ VARCHAR(14)
    , SITUACAO_ID INT
    , DATA_CRIACAO SMALLDATETIME DEFAULT GETDATE()
    , USER_CRIACAO INT
);
GO

CREATE TABLE SEGURADORA (
    SEGURADORA_ID INT IDENTITY(1,1)
    , NOME VARCHAR(100)
    , CNPJ VARCHAR(14)
    , SITUACAO_ID INT
    , DATA_CRIACAO SMALLDATETIME DEFAULT GETDATE()
    , USER_CRIACAO INT
);
GO

CREATE TABLE SEGURADO (
    SEGURADO_ID INT IDENTITY(1,1)
    , NOME VARCHAR(200)
    , CPF VARCHAR(11)
    , BANCO VARCHAR(100)
    , AGENCIA VARCHAR(4)
    , DIGITO_AGENCIA CHAR
    , CONTA VARCHAR(10)
    , DIGITO_CONTA CHAR
    , BENEFICIARIO VARCHAR(200)
    , CPF_BENEFICIARIO VARCHAR(11)
    , EMAIL VARCHAR(100)
    , SITUACAO_ID INT
    , DATA_CRIACAO SMALLDATETIME DEFAULT GETDATE()
);
GO

CREATE TABLE TIPO_COBERTURA (
    TIPO_COBERTURA_ID INT IDENTITY(1,1)
    , NOME VARCHAR(200)
    , SITUACAO_ID TINYINT
);
GO

CREATE TABLE SITUACAO (
    SITUACAO_ID INT IDENTITY(1,1)
    , NOME VARCHAR(100)
);
GO

CREATE TABLE NOTA_DEBITO (
    NOTA_DEBITO INT IDENTITY(1,1)
    , SPONSOR VARCHAR(100)
    , NOTA VARCHAR(20)
    , DATA_EMISSAO SMALLDATETIME
    , SEGURADORA_ID INT
    , DATA_ENVIO SMALLDATETIME
    , PREVISAO_PAGAMENTO SMALLDATETIME
    , DATA_PAGAMENTO SMALLDATETIME
    , OBSERVACAO VARCHAR(4000)
    , VALOR_DOLAR MONEY
    , VALOR_DOLAR_DESCONTO MONEY
    , FEES_DOLAR MONEY
    , VALOR_REAL MONEY
    , VALOR_REAL_DESCONTO MONEY
    --, CAMBIO MONEY
    --, FEES_REAL MONEY
    , REFERENCIA VARCHAR(100)
    , SEGURADO_ID INT
    , SINISTRO_ID INT
    , TIPO_MOEDA_ID INT
    , DATA_REPASSE_REMESSA SMALLDATETIME
    , DATA_EMAIL SMALLDATETIME
    , EMISSOR_ID INT
    , DIAS_SEM_PAGAMENTO SMALLDATETIME
    , REMESSA_DOLAR MONEY
    , DOLAR_BANCO_CENTRAL MONEY
    --, U$ MONEY
    --, SALDO_REMESSA MONEY
    --, SPREAD_REMESSA REAL
    --, SPREAD_ND REAL
    --, DOLAR_BC_ND MONEY
    --, DIFF_ND_BC_ND_WTA MONEY
    --, SPREAD_ND_WTA_BC REAL
    --, DOLAR_ND_CC MONEY
    --, DIFF_ND_CC_ND_WTA MONEY
    --, SPREAD_ND_WTA_CC REAL
    , COMISSAO_WTA MONEY
    --, NF BIT
    , 
);
GO

CREATE TABLE TIPO_MOEDA (
    TIPO_MOEDA_ID INT IDENTITY(1,1)
    , NOME VARCHAR(20)
    , NOME_ABREVIADO VARCHAR(5)
    , SITUACAO_ID INT
);
GO

CREATE TABLE EMISSOR (
    EMISSOR_ID INT IDENTITY(1,1)
    , NOME VARCHAR(200)
);
GO