
IF OBJECT_ID('UP_CENTRO_CUSTO_ATUALIZAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_CENTRO_CUSTO_ATUALIZAR;
GO

CREATE PROCEDURE UP_CENTRO_CUSTO_ATUALIZAR (
	@ID INT
	, @NOME VARCHAR(100) = NULL
)
AS
SET NOCOUNT ON;

UPDATE	CENTRO_CUSTO
SET		NOME = ISNULL(NULLIF(@NOME, ''), NOME)
WHERE	ID = @ID
;
GO
