
IF OBJECT_ID('fin.UP_CATEGORIA_DELETAR', 'P') IS NOT NULL
	DROP PROCEDURE fin.UP_CATEGORIA_DELETAR;
GO

CREATE PROCEDURE fin.UP_CATEGORIA_DELETAR (
	@ID INT
)
AS
SET NOCOUNT ON;

UPDATE fin.CATEGORIA SET ATIVO = 0 WHERE ID = @ID
;
GO
