
IF OBJECT_ID('UP_CAP_CLIENTE_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_CAP_CLIENTE_BUSCAR;
GO

CREATE PROCEDURE UP_CAP_CLIENTE_BUSCAR (
	@ID INT = NULL
	, @NOME VARCHAR(100) = NULL
	, @ATIVO BIT = 1
	, @SEGURADORA_ID INT = 0
)
AS
SET NOCOUNT ON;

SELECT	CLI.ID AS ID
		, CLI.NOME AS NOME
		, CLI.ATIVO AS ATIVO
		, S.ID AS SEGURADORA_ID
		, S.NOME AS SEGURADORA_NOME
		, dbo.UF_FORMATAR_CPF_CNPJ(S.CNPJ) AS SEGURADORA_CNPJ
FROM	CAP_CLIENTE CLI
LEFT	JOIN SEGURADORA S
		ON S.ID = CLI.SEGURADORA_ID
		AND S.ID = ISNULL(@SEGURADORA_ID, S.ID)
WHERE	CLI.ID = ISNULL(NULLIF(@ID, 0), CLI.ID)
		AND CLI.ATIVO = ISNULL(@ATIVO, CLI.ATIVO)
		AND CLI.NOME = ISNULL(NULLIF(@NOME, ''), CLI.NOME)
;
GO
