
IF OBJECT_ID('UP_COMPANHIA_CADASTRAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_COMPANHIA_CADASTRAR;
GO

CREATE PROCEDURE UP_COMPANHIA_CADASTRAR (
	@NOME VARCHAR(100)
	, @CNPJ VARCHAR(14)
)
AS
SET NOCOUNT ON;

INSERT	INTO COMPANHIA (NOME, CNPJ)
SELECT	TRIM(@NOME), RIGHT(CONCAT('00000000000000', @CNPJ), 14)
;
GO
