
IF OBJECT_ID('UP_CAP_CLIENTE_CADASTRAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_CAP_CLIENTE_CADASTRAR;
GO

CREATE PROCEDURE UP_CAP_CLIENTE_CADASTRAR (
	@NOME VARCHAR(100)
	, @SEGURADORA_ID INT
)
AS
SET NOCOUNT ON;

IF ISNULL(@NOME, '') <> ''
	INSERT INTO CAP_CLIENTE (NOME, SEGURADORA_ID) SELECT TRIM(@NOME), @SEGURADORA_ID
GO
