
IF OBJECT_ID('UP_COMPANHIA_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_COMPANHIA_BUSCAR;
GO

CREATE PROCEDURE UP_COMPANHIA_BUSCAR (
	@ID INT = NULL
	, @APENAS_ATIVO BIT = 1
)
AS
SET NOCOUNT ON;

GO
