
IF OBJECT_ID('fin.UP_CLIENTE_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE fin.UP_CLIENTE_BUSCAR;
GO

CREATE PROCEDURE fin.UP_CLIENTE_BUSCAR (
	@ID INT = NULL
	, @NOME VARCHAR(100) = NULL
	, @NUM_DOCUMENTO VARCHAR(14) = NULL
	, @ATIVO BIT = 1
	, @SEGURADORA_ID INT = 0
)
AS
SET NOCOUNT ON;

SELECT	CLI.ID AS ID
		, CLI.NOME AS NOME
		, CLI.ATIVO AS ATIVO
		, S.ID AS SEGURADORA_ID
		, S.NOME AS SEGURADORA_NOME
		, dbo.UF_FORMATAR_CPF_CNPJ(S.CNPJ) AS SEGURADORA_CNPJ
FROM	fin.CLIENTE CLI
LEFT	JOIN dbo.SEGURADORA S
		ON S.ID = CLI.SEGURADORA_ID
		AND S.ID = CASE WHEN @SEGURADORA_ID = 0 THEN NULL ELSE ISNULL(@SEGURADORA_ID, S.ID) END
WHERE	CLI.ID = ISNULL(@ID, CLI.ID)
		AND CLI.ATIVO = ISNULL(@ATIVO, CLI.ATIVO)
		AND CLI.NOME = ISNULL(@NOME, CLI.NOME)
;
GO
