
IF OBJECT_ID('UP_CENTRO_CUSTO_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_CENTRO_CUSTO_BUSCAR;
GO

CREATE PROCEDURE UP_CENTRO_CUSTO_BUSCAR (
	@ID INT = NULL
	, @NOME VARCHAR(100) = NULL
	, @ATIVO BIT = 1
)
AS
SET NOCOUNT ON;

SELECT	CC.ID AS ID
		, CC.NOME AS NOME
FROM	CENTRO_CUSTO CC
WHERE	CC.ID = ISNULL(NULLIF(@ID, 0), CC.ID)
		AND CC.ATIVO = ISNULL(@ATIVO, CC.ATIVO)
		AND CC.NOME = ISNULL(NULLIF(@NOME, ''), CC.NOME)
;
GO
