
IF OBJECT_ID('fin.UP_CATEGORIA_CADASTRAR', 'P') IS NOT NULL
	DROP PROCEDURE fin.UP_CATEGORIA_CADASTRAR;
GO

CREATE PROCEDURE fin.UP_CATEGORIA_CADASTRAR (
	@NOME VARCHAR(100)
	, @TIPO_LANCAMENTO_ID INT
)
AS
SET NOCOUNT ON;

IF (ISNULL(@NOME, '') <> '' AND ISNULL(@TIPO_LANCAMENTO_ID, 0) <> 0)
	INSERT INTO fin.CATEGORIA (NOME, TIPO_LANCAMENTO_ID) SELECT LTRIM(RTRIM(@NOME)), @TIPO_LANCAMENTO_ID
GO
