
IF OBJECT_ID('UP_CATEGORIA_CADASTRAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_CATEGORIA_CADASTRAR;
GO

CREATE PROCEDURE UP_CATEGORIA_CADASTRAR (
	@NOME VARCHAR(100)
	, @TIPO_LANCAMENTO_ID INT
)
AS
SET NOCOUNT ON;

IF (ISNULL(@NOME, '') <> '' AND ISNULL(@TIPO_LANCAMENTO_ID, 0) <> 0)
	INSERT INTO CATEGORIA (NOME, TIPO_LANCAMENTO_ID) SELECT TRIM(@NOME), @TIPO_LANCAMENTO_ID
GO
