
IF OBJECT_ID('UP_CAP_CONTA_DELETAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_CAP_CONTA_DELETAR;
GO

CREATE PROCEDURE UP_CAP_CONTA_DELETAR (
	@ID INT
)
AS
SET NOCOUNT ON;

UPDATE CAP_CONTA SET ATIVO = 0 WHERE ID = @ID
;
GO
