
IF OBJECT_ID('fin.UP_CONTA_BANCARIA_DELETAR', 'P') IS NOT NULL
	DROP PROCEDURE fin.UP_CONTA_BANCARIA_DELETAR;
GO

CREATE PROCEDURE fin.UP_CONTA_BANCARIA_DELETAR (
	@ID INT
)
AS
SET NOCOUNT ON;

UPDATE fin.CONTA_BANCARIA SET ATIVO = 0 WHERE ID = @ID
;
GO
