
IF OBJECT_ID('fin.UP_CENTRO_CUSTO_ATUALIZAR', 'P') IS NOT NULL
	DROP PROCEDURE fin.UP_CENTRO_CUSTO_ATUALIZAR;
GO

CREATE PROCEDURE fin.UP_CENTRO_CUSTO_ATUALIZAR (
	@ID INT
	, @NOME VARCHAR(100) = NULL
)
AS
SET NOCOUNT ON;

UPDATE	fin.CENTRO_CUSTO
SET		NOME = ISNULL(NULLIF(@NOME, ''), NOME)
WHERE	ID = @ID
;
GO
