
IF OBJECT_ID('UP_CAP_CONTA_CADASTRAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_CAP_CONTA_CADASTRAR;
GO

CREATE PROCEDURE UP_CAP_CONTA_CADASTRAR (
	@NOME VARCHAR(100)
	, @BANCO VARCHAR(100) = NULL
	, @AGENCIA VARCHAR(4) = NULL
	, @DIGITO_AGENCIA CHAR = NULL
	, @CONTA VARCHAR(10) = NULL
	, @DIGITO_CONTA CHAR = NULL
	, @BENEFICIARIO VARCHAR(100) = NULL
	, @CPF_BENEFICIARIO VARCHAR(14) = NULL
	, @EMAIL VARCHAR(100) = NULL
	, @CONTA_CADASTRADA BIT = NULL
	, @SALDO MONEY = 0
)
AS
SET NOCOUNT ON;

IF ISNULL(@NOME, '') <> ''
BEGIN
	INSERT INTO CAP_CONTA (
		NOME, BANCO, AGENCIA, DIGITO_AGENCIA, CONTA, DIGITO_CONTA, SALDO
	)
	SELECT TRIM(@NOME), ISNULL(@BANCO, ''), ISNULL(@AGENCIA, ''), ISNULL(@DIGITO_AGENCIA, '')
			, ISNULL(@CONTA, ''), ISNULL(@DIGITO_CONTA, ''), ISNULL(@SALDO, 0)
END
GO
