
IF OBJECT_ID('fin.UP_CLIENTE_ATUALIZAR', 'P') IS NOT NULL
	DROP PROCEDURE fin.UP_CLIENTE_ATUALIZAR;
GO

CREATE PROCEDURE fin.UP_CLIENTE_ATUALIZAR (
	@ID INT
	, @NOME VARCHAR(100) = NULL
	, @NUM_DOCUMENTO VARCHAR(14) = NULL
	, @SEGURADORA_ID INT = 0
)
AS
SET NOCOUNT ON;

UPDATE	fin.CLIENTE
SET		NOME = ISNULL(NULLIF(@NOME, ''), NOME)
		, SEGURADORA_ID = CASE WHEN @SEGURADORA_ID = 0 THEN SEGURADORA_ID ELSE @SEGURADORA_ID END
WHERE	ID = @ID
;
GO
