
IF OBJECT_ID('UP_CATEGORIA_ATUALIZAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_CATEGORIA_ATUALIZAR;
GO

CREATE PROCEDURE UP_CATEGORIA_ATUALIZAR (
	@ID INT
	, @NOME VARCHAR(100) = NULL
	, @TIPO_LANCAMENTO_ID INT = NULL
)
AS
SET NOCOUNT ON;

UPDATE	CATEGORIA
SET		NOME = ISNULL(NULLIF(@NOME, ''), NOME)
		, TIPO_LANCAMENTO_ID = ISNULL(NULLIF(@TIPO_LANCAMENTO_ID, 0), TIPO_LANCAMENTO_ID)
WHERE	ID = @ID
;
GO
