
IF OBJECT_ID('fin.UP_CENTRO_CUSTO_CADASTRAR', 'P') IS NOT NULL
	DROP PROCEDURE fin.UP_CENTRO_CUSTO_CADASTRAR;
GO

CREATE PROCEDURE fin.UP_CENTRO_CUSTO_CADASTRAR (
	@NOME VARCHAR(100)
)
AS
SET NOCOUNT ON;

IF ISNULL(@NOME, '') <> ''
	INSERT INTO fin.CENTRO_CUSTO (NOME) SELECT LTRIM(RTRIM(@NOME));
GO
