
IF OBJECT_ID('fin.UP_CENTRO_CUSTO_DELETAR', 'P') IS NOT NULL
	DROP PROCEDURE fin.UP_CENTRO_CUSTO_DELETAR;
GO

CREATE PROCEDURE fin.UP_CENTRO_CUSTO_DELETAR (
	@ID INT
)
AS
SET NOCOUNT ON;

UPDATE	fin.CENTRO_CUSTO SET ATIVO = 0 WHERE ID = @ID
;
GO
