
IF OBJECT_ID('UP_CAP_CLIENTE_DELETAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_CAP_CLIENTE_DELETAR;
GO

CREATE PROCEDURE UP_CAP_CLIENTE_DELETAR (
	@ID INT
)
AS
SET NOCOUNT ON;

UPDATE CAP_CLIENTE SET ATIVO = 0 WHERE ID = @ID
;
GO
