
IF OBJECT_ID('UP_CATEGORIA_DELETAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_CATEGORIA_DELETAR;
GO

CREATE PROCEDURE UP_CATEGORIA_DELETAR (
	@ID INT
)
AS
SET NOCOUNT ON;

UPDATE CATEGORIA SET ATIVO = 0 WHERE ID = @ID
;
GO
