
IF OBJECT_ID('UP_FECHAMENTO_DELETAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_FECHAMENTO_DELETAR;
GO

CREATE PROCEDURE UP_FECHAMENTO_DELETAR (
	@ID INT
)
AS
SET NOCOUNT ON;

UPDATE FECHAMENTO SET ATIVO = 0 WHERE ID = @ID;
GO
