
IF OBJECT_ID('UP_FORNECEDOR_CADASTRAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_FORNECEDOR_CADASTRAR;
GO

CREATE PROCEDURE UP_FORNECEDOR_CADASTRAR (
	@NOME VARCHAR(100)
	, @CNPJ VARCHAR(4) = NULL
)
AS
SET NOCOUNT ON;

IF ISNULL(@NOME, '') <> ''
	INSERT INTO FORNECEDOR (NOME, CNPJ) SELECT TRIM(@NOME), dbo.UF_TAMANHO_CPF_CNPJ(ISNULL(@CNPJ, ''))
GO
