
IF OBJECT_ID('fin.UP_FECHAMENTO_CADASTRAR', 'P') IS NOT NULL
	DROP PROCEDURE fin.UP_FECHAMENTO_CADASTRAR;
GO

CREATE PROCEDURE fin.UP_FECHAMENTO_CADASTRAR (
	@DATA_FECHAMENTO SMALLDATETIME = NULL
	, @REMESSA BIT = NULL
	, @DOLAR_REMESSA MONEY = NULL
	, @EMISSOR_ID INT = NULL
)
AS
SET NOCOUNT ON;

INSERT	INTO fin.FECHAMENTO (DATA_FECHAMENTO, REMESSA, DOLAR_REMESSA, EMISSOR_ID)
SELECT	@DATA_FECHAMENTO, ISNULL(@REMESSA, 0), @DOLAR_REMESSA, @EMISSOR_ID
;
GO
