
IF OBJECT_ID('UP_FECHAMENTO_CADASTRAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_FECHAMENTO_CADASTRAR;
GO

CREATE PROCEDURE UP_FECHAMENTO_CADASTRAR (
	@DATA_FECHAMENTO SMALLDATETIME = NULL
	, @REMESSA BIT = NULL
)
AS
SET NOCOUNT ON;

INSERT	INTO FECHAMENTO (DATA_FECHAMENTO, REMESSA)
SELECT	@DATA_FECHAMENTO, ISNULL(@REMESSA, 0)
GO
