
IF OBJECT_ID('fin.UP_FECHAMENTO_ATUALIZAR', 'P') IS NOT NULL
	DROP PROCEDURE fin.UP_FECHAMENTO_ATUALIZAR;
GO

CREATE PROCEDURE fin.UP_FECHAMENTO_ATUALIZAR (
	@ID INT
	, @DATA_FECHAMENTO SMALLDATETIME = NULL
	, @REMESSA BIT = NULL
	, @DOLAR_REMESSA MONEY = NULL
	, @EMISSOR_ID INT = NULL
)
AS
SET NOCOUNT ON;

UPDATE	fin.FECHAMENTO
SET		DATA_FECHAMENTO = ISNULL(@DATA_FECHAMENTO, DATA_FECHAMENTO)
		, REMESSA = ISNULL(@REMESSA, REMESSA)
		, @DOLAR_REMESSA = ISNULL(@DOLAR_REMESSA, DOLAR_REMESSA)
		, @EMISSOR_ID = ISNULL(@EMISSOR_ID, EMISSOR_ID)
WHERE	ID = @ID
GO
