
IF OBJECT_ID('fin.UP_FECHAMENTO_DELETAR', 'P') IS NOT NULL
	DROP PROCEDURE fin.UP_FECHAMENTO_DELETAR;
GO

CREATE PROCEDURE fin.UP_FECHAMENTO_DELETAR (
	@ID INT
)
AS
SET NOCOUNT ON;

DELETE FROM fin.FECHAMENTO WHERE ID = @ID;
GO
