
IF OBJECT_ID('UP_FECHAMENTO_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_FECHAMENTO_BUSCAR;
GO

CREATE PROCEDURE UP_FECHAMENTO_BUSCAR (
	@ID INT = NULL
	, @ATIVO BIT = NULL
	, @DATA_FECHAMENTO SMALLDATETIME = NULL
	, @REMESSA BIT = NULL
)
AS
SET NOCOUNT ON;

SELECT	FE.ID AS ID
		, FE.ATIVO AS ATIVO
		, FE.REMESSA AS REMESSA
		, FE.DATA_FECHAMENTO AS DATA_FECHAMENTO
FROM	FECHAMENTO FE
WHERE	FE.ID = ISNULL(@ID, FE.ID)
		AND FE.ATIVO = ISNULL(@ATIVO, FE.ATIVO)
		AND FE.REMESSA = ISNULL(@REMESSA, FE.REMESSA)
		AND FE.DATA_FECHAMENTO = ISNULL(@DATA_FECHAMENTO, FE.DATA_FECHAMENTO)
GO
