
IF OBJECT_ID('fin.UP_FORNECEDOR_ATUALIZAR', 'P') IS NOT NULL
	DROP PROCEDURE fin.UP_FORNECEDOR_ATUALIZAR;
GO

CREATE PROCEDURE fin.UP_FORNECEDOR_ATUALIZAR (
	@ID INT
	, @NOME VARCHAR(100) = NULL
	, @CNPJ VARCHAR(4) = NULL
)
AS
SET NOCOUNT ON;

UPDATE	fin.FORNECEDOR
SET		NOME = ISNULL(NULLIF(@NOME, ''), NOME)
		, CNPJ = dbo.UF_TAMANHO_CPF_CNPJ(ISNULL(@CNPJ, ''))
WHERE	ID = @ID
;
GO
