
IF OBJECT_ID('fin.UP_FECHAMENTO_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE fin.UP_FECHAMENTO_BUSCAR;
GO

CREATE PROCEDURE fin.UP_FECHAMENTO_BUSCAR (
	@ID INT = NULL
	, @DATA_FECHAMENTO SMALLDATETIME = NULL
	, @REMESSA BIT = NULL
	, @DOLAR_REMESSA MONEY = NULL
	, @EMISSOR_ID INT = 0
)
AS
SET NOCOUNT ON;

SELECT	FE.ID AS ID
		, FE.REMESSA AS REMESSA
		, FE.DATA_FECHAMENTO AS DATA_FECHAMENTO
		, FORMAT(FE.DATA_FECHAMENTO, 'dd/MM/yyyy hh:mm:ss', 'pt-BR') AS DATA_FECHAMENTO_FORMATADA
		, FE.DOLAR_REMESSA AS DOLAR_REMESSA
		, FE.EMISSOR_ID AS EMISSOR_ID
		, E.NOME AS EMISSOR_NOME
FROM	fin.FECHAMENTO FE
LEFT	JOIN dbo.EMISSOR E
		ON E.ID = FE.EMISSOR_ID
		AND E.ID = CASE WHEN @EMISSOR_ID = 0 THEN NULL ELSE @EMISSOR_ID END
WHERE	FE.ID = ISNULL(@ID, FE.ID)
		AND FE.REMESSA = ISNULL(@REMESSA, FE.REMESSA)
		AND CAST(FE.DATA_FECHAMENTO AS date) = CAST(ISNULL(@DATA_FECHAMENTO, FE.DATA_FECHAMENTO) AS date)
		AND FE.DOLAR_REMESSA = ISNULL(@DOLAR_REMESSA, FE.DOLAR_REMESSA)
GO
