
IF OBJECT_ID('UP_FORNECEDOR_DELETAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_FORNECEDOR_DELETAR;
GO

CREATE PROCEDURE UP_FORNECEDOR_DELETAR (
	@ID INT
)
AS
SET NOCOUNT ON;

UPDATE FORNECEDOR SET ATIVO = 0 WHERE ID = @ID
;
GO
