
IF OBJECT_ID('fin.UP_FORNECEDOR_CADASTRAR', 'P') IS NOT NULL
	DROP PROCEDURE fin.UP_FORNECEDOR_CADASTRAR;
GO

CREATE PROCEDURE fin.UP_FORNECEDOR_CADASTRAR (
	@NOME VARCHAR(100)
	, @CNPJ VARCHAR(14) = NULL
)
AS
SET NOCOUNT ON;

IF ISNULL(@NOME, '') <> ''
	INSERT INTO fin.FORNECEDOR (NOME, CNPJ) SELECT LTRIM(RTRIM(@NOME)), dbo.UF_TAMANHO_CPF_CNPJ(ISNULL(@CNPJ, ''))
GO
