
IF OBJECT_ID('UP_FORNECEDOR_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_FORNECEDOR_BUSCAR;
GO

CREATE PROCEDURE UP_FORNECEDOR_BUSCAR (
	@ID INT = NULL
	, @NOME VARCHAR(100) = NULL
	, @ATIVO BIT = 1
	, @CNPJ VARCHAR(4) = NULL
)
AS
SET NOCOUNT ON;

SELECT	ID AS ID
		, NOME AS NOME
		, ATIVO AS ATIVO
		, dbo.UF_FORMATAR_CPF_CNPJ(@CNPJ) AS CNPJ
FROM	FORNECEDOR
WHERE	ID = ISNULL(NULLIF(@ID, 0), ID)
		AND ATIVO = ISNULL(@ATIVO, ATIVO)
		AND NOME = ISNULL(NULLIF(@NOME, ''), NOME)
		AND CNPJ = ISNULL(@CNPJ, CNPJ)
;
GO
