
IF OBJECT_ID('UP_FECHAMENTO_ATUALIZAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_FECHAMENTO_ATUALIZAR;
GO

CREATE PROCEDURE UP_FECHAMENTO_ATUALIZAR (
	@ID INT
	, @DATA_FECHAMENTO SMALLDATETIME = NULL
	, @REMESSA BIT = NULL
)
AS
SET NOCOUNT ON;

UPDATE	FECHAMENTO
SET		DATA_FECHAMENTO = ISNULL(@DATA_FECHAMENTO, DATA_FECHAMENTO)
		, REMESSA = ISNULL(@REMESSA, REMESSA)
WHERE	ID = @ID
GO
