
IF OBJECT_ID('imp.UP_IMPORTACAO_DELETAR', 'P') IS NOT NULL
	DROP PROCEDURE imp.UP_IMPORTACAO_DELETAR;
GO

CREATE PROCEDURE imp.UP_IMPORTACAO_DELETAR (
	@ID INT
)
AS
SET NOCOUNT ON;

UPDATE imp.IMPORTACAO SET ATIVO = 0 WHERE ID = @ID;
GO
