
IF OBJECT_ID('imp.UP_IMPORTACAO_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE imp.UP_IMPORTACAO_BUSCAR;
GO

CREATE PROCEDURE imp.UP_IMPORTACAO_BUSCAR (
	@ID INT = NULL
	, @SEGURADORA_ID INT = NULL
	, @NOME_ARQUIVO VARCHAR(300) = NULL
	, @ANTECIPACAO BIT = NULL
	, @ATIVO BIT = 1
)
AS
SET NOCOUNT ON;

SELECT	IMP.ID AS ID
		, IMP.SEGURADORA_ID AS SEGURADORA_ID
		, S.NOME AS SEGURADORA_NOME
		, S.CNPJ AS SEGURADORA_CNPJ
		, S.CONTROLA_ANTECIPACAO AS CONTROLA_ANTECIPACAO
		, IMP.ATIVO AS ATIVO
		, IMP.ANTECIPACAO AS ANTECIPACAO
		, IMP.NOME_ARQUIVO AS NOME_ARQUIVO
		, IMP.CAMINHO_ARQUIVO AS CAMINHO_ATIVO
FROM	imp.IMPORTACAO IMP
INNER	JOIN dbo.SEGURADORA S
		ON S.ID = IMP.SEGURADORA_ID
		AND S.ID = ISNULL(@SEGURADORA_ID, S.ID)
WHERE	IMP.ID = ISNULL(@ID, IMP.ID)
		AND IMP.ATIVO = ISNULL(@ATIVO, IMP.ATIVO)
		AND IMP.ANTECIPACAO = ISNULL(@ANTECIPACAO, IMP.ANTECIPACAO)
		AND IMP.NOME_ARQUIVO = ISNULL(@NOME_ARQUIVO, IMP.NOME_ARQUIVO)
;
GO
