
IF OBJECT_ID('UP_IMPORTACAO_SINISTRO_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_IMPORTACAO_SINISTRO_BUSCAR;
GO

CREATE PROCEDURE UP_IMPORTACAO_SINISTRO_BUSCAR (
	@ID INT = NULL
	, @SEGURADORA_ID INT = NULL
	, @NOME_ARQUIVO VARCHAR(300) = NULL
	, @ANTECIPACAO BIT = NULL
	, @ATIVO BIT = 1
)
AS
SET NOCOUNT ON;

SELECT	IMP.ID AS ID
		, IMP.SEGURADORA_ID AS SEGURADORA_ID
		, S.NOME AS SEGURADORA_NOME
		, S.CNPJ AS SEGURADORA_CNPJ
		, S.CONTROLA_ANTECIPACAO AS CONTROLA_ANTECIPACAO
		, IMP.ATIVO AS ATIVO
		, IMP.ANTECIPACAO AS ANTECIPACAO
		, IMP.NOME_ARQUIVO AS NOME_ARQUIVO
		, IMP.CAMINHO_ARQUIVO AS CAMINHO_ATIVO
INTO	#IMPORTACAO
FROM	IMPORTACAO_SINISTRO IMP
INNER	JOIN SEGURADORA S
		ON S.ID = IMP.SEGURADORA_ID
		AND S.ID = ISNULL(NULLIF(@SEGURADORA_ID, 0), S.ID)
WHERE	IMP.ID = ISNULL(NULLIF(@ID, 0), IMP.ID)
		AND IMP.ATIVO = ISNULL(@ATIVO, IMP.ATIVO)
		AND IMP.ANTECIPACAO = ISNULL(@ANTECIPACAO, IMP.ANTECIPACAO)
		AND IMP.NOME_ARQUIVO = ISNULL(NULLIF(@NOME_ARQUIVO, ''), IMP.NOME_ARQUIVO)
;

SELECT	* FROM #IMPORTACAO;
DROP	TABLE #IMPORTACAO;
GO
