
IF OBJECT_ID('UP_LANCAMENTO_CADASTRAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_LANCAMENTO_CADASTRAR;
GO

CREATE PROCEDURE UP_LANCAMENTO_CADASTRAR (
	@DESCRICAO VARCHAR(100)
	, @FORNCEDOR_ID INT
	, @CATEGORIA_ID INT
	, @CENTRO_CUSTO_ID INT
	, @CUSTO_FIXO BIT
	, @VALOR MONEY
	, @DATA_LANCAMENTO SMALLDATETIME
)
AS
SET NOCOUNT ON;

INSERT INTO LANCAMENTO (
	DESCRICAO, FORNCEDOR_ID, CATEGORIA_ID, CENTRO_CUSTO_ID, CUSTO_FIXO, VALOR, DATA_LANCAMENTO
)
SELECT TRIM(ISNULL(@DESCRICAO, '')), @FORNCEDOR_ID, @CATEGORIA_ID, @CENTRO_CUSTO_ID, @CUSTO_FIXO, @VALOR, @DATA_LANCAMENTO
GO
