
IF OBJECT_ID('fin.UP_LANCAMENTO_ATUALIZAR', 'P') IS NOT NULL
	DROP PROCEDURE fin.UP_LANCAMENTO_ATUALIZAR;
GO

CREATE PROCEDURE fin.UP_LANCAMENTO_ATUALIZAR (
	@ID INT
	, @DESCRICAO VARCHAR(100) = NULL
	, @ATIVO BIT = NULL
	, @CUSTO_FIXO BIT = NULL
	, @VALOR MONEY = NULL
	, @DATA_LANCAMENTO SMALLDATETIME = NULL
	, @FECHAMENTO_ID INT = 0
	, @CLIENTE_ID INT = NULL
	, @CONTA_BANCARIA_ID INT = NULL
	, @CENTRO_CUSTO_ID INT = NULL
	, @CATEGORIA_ID INT = NULL
	, @FORNECEDOR_ID INT = NULL
)
AS
SET NOCOUNT ON;

UPDATE	fin.LANCAMENTO
SET		DESCRICAO = ISNULL(NULLIF(@DESCRICAO, ''), DESCRICAO)
		, FORNECEDOR_ID = ISNULL(@FORNECEDOR_ID, FORNECEDOR_ID)
		, CATEGORIA_ID = ISNULL(@CATEGORIA_ID, CATEGORIA_ID)
		, CENTRO_CUSTO_ID = ISNULL(@CENTRO_CUSTO_ID, CENTRO_CUSTO_ID)
		, CUSTO_FIXO = ISNULL(@CUSTO_FIXO, CUSTO_FIXO)
		, VALOR = ISNULL(@VALOR, VALOR)
		, DATA_LANCAMENTO = ISNULL(@DATA_LANCAMENTO, DATA_LANCAMENTO)
		, CLIENTE_ID = ISNULL(@CLIENTE_ID, CLIENTE_ID)
		, CONTA_BANCARIA_ID = ISNULL(@CONTA_BANCARIA_ID, CONTA_BANCARIA_ID)
		, FECHAMENTO_ID = @FECHAMENTO_ID
WHERE	ID = @ID
;
GO
