
IF OBJECT_ID('fin.UP_LANCAMENTO_CADASTRAR', 'P') IS NOT NULL
	DROP PROCEDURE fin.UP_LANCAMENTO_CADASTRAR;
GO

CREATE PROCEDURE fin.UP_LANCAMENTO_CADASTRAR (
	@DESCRICAO VARCHAR(100)
	, @CUSTO_FIXO BIT = NULL
	, @VALOR MONEY = NULL
	, @DATA_LANCAMENTO SMALLDATETIME = NULL
	, @FECHAMENTO_ID INT = 0
	, @CLIENTE_ID INT = NULL
	, @CONTA_BANCARIA_ID INT = NULL
	, @CENTRO_CUSTO_ID INT = NULL
	, @CATEGORIA_ID INT = NULL
	, @FORNECEDOR_ID INT = NULL
)
AS
SET NOCOUNT ON;

INSERT INTO fin.LANCAMENTO (
	DESCRICAO, FORNECEDOR_ID, CATEGORIA_ID, CENTRO_CUSTO_ID
	, CONTA_BANCARIA_ID, CLIENTE_ID, FECHAMENTO_ID, DATA_LANCAMENTO, CUSTO_FIXO, VALOR
)
SELECT	LTRIM(RTRIM(ISNULL(@DESCRICAO, ''))), @FORNECEDOR_ID, @CATEGORIA_ID, @CENTRO_CUSTO_ID
		, @CONTA_BANCARIA_ID, @CLIENTE_ID, @FECHAMENTO_ID, @DATA_LANCAMENTO, @CUSTO_FIXO, @VALOR
GO
