
IF OBJECT_ID('fin.UP_LANCAMENTO_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE fin.UP_LANCAMENTO_BUSCAR;
GO

CREATE PROCEDURE fin.UP_LANCAMENTO_BUSCAR (
	@ID INT = NULL
	, @DESCRICAO VARCHAR(100) = NULL
	, @ATIVO BIT = NULL
	, @CUSTO_FIXO BIT = NULL
	, @VALOR MONEY = NULL
	, @DATA_LANCAMENTO SMALLDATETIME = NULL
	, @FECHAMENTO_ID INT = 0
	, @CLIENTE_ID INT = NULL
	, @CONTA_BANCARIA_ID INT = NULL
	, @CENTRO_CUSTO_ID INT = NULL
	, @CATEGORIA_ID INT = NULL
	, @FORNECEDOR_ID INT = NULL
)
AS
SET NOCOUNT ON;

SELECT	L.ID AS ID
		, L.DESCRICAO AS DESCRICAO
		, L.ATIVO AS ATIVO
		, L.FORNECEDOR_ID AS FORNCEDOR_ID
		, F.NOME AS FORNECEDOR_NOME
		, L.CATEGORIA_ID AS CATEGORIA_ID
		, C.NOME AS CATEGORIA_NOME
		, L.CENTRO_CUSTO_ID AS CENTRO_CUSTO_ID
		, CC.NOME AS CENTRO_CUSTO_NOME
		, L.CLIENTE_ID AS CLIENTE_ID
		, CLI.NOME AS CLIENTE_NOME
		, L.CONTA_BANCARIA_ID AS CONTA_BANCARIA_ID
		, CB.NOME AS CONTA_BANCARIA_NOME
		, L.FORNECEDOR_ID AS FORNECEDOR_ID
		, F.NOME AS FORNECEDOR_NOME
		, ISNULL(L.FECHAMENTO_ID, 0) AS FECHAMENTO_ID
		, L.CUSTO_FIXO AS CUSTO_FIXO
		, L.VALOR AS VALOR
		, L.DATA_LANCAMENTO AS DATA_LANCAMENTO
		, CONVERT(varchar, L.DATA_LANCAMENTO, 103) AS DATA_LANCAMENTO_FORMATADA
FROM	fin.LANCAMENTO L
INNER	JOIN fin.CATEGORIA C
		ON C.ID = L.CATEGORIA_ID
INNER	JOIN fin.CENTRO_CUSTO CC
		ON CC.ID = L.CENTRO_CUSTO_ID
INNER	JOIN fin.CLIENTE CLI
		ON CLI.ID = L.CLIENTE_ID
INNER	JOIN fin.CONTA_BANCARIA CB
		ON CB.ID = L.CONTA_BANCARIA_ID
INNER	JOIN fin.FORNECEDOR F
		ON F.ID = L.FORNECEDOR_ID
LEFT	JOIN fin.FECHAMENTO FE
		ON FE.ID = L.FECHAMENTO_ID
WHERE	L.ID = ISNULL(@ID, L.ID)
		AND L.ATIVO = ISNULL(@ATIVO, L.ATIVO)
		AND L.DESCRICAO = ISNULL(@DESCRICAO, L.DESCRICAO)
		AND L.FORNECEDOR_ID = ISNULL(@FORNECEDOR_ID, L.FORNECEDOR_ID)
		AND L.CATEGORIA_ID = ISNULL(@CATEGORIA_ID, L.CATEGORIA_ID)
		AND L.CENTRO_CUSTO_ID = ISNULL(@CENTRO_CUSTO_ID, L.CENTRO_CUSTO_ID)
		AND L.CUSTO_FIXO = ISNULL(@CUSTO_FIXO, L.CUSTO_FIXO)
		AND L.VALOR = ISNULL(@VALOR, L.VALOR)
		AND L.DATA_LANCAMENTO = ISNULL(@DATA_LANCAMENTO, L.DATA_LANCAMENTO)
		AND L.FECHAMENTO_ID = CASE WHEN @FECHAMENTO_ID = 0 THEN L.FECHAMENTO_ID ELSE @FECHAMENTO_ID END
		AND L.CLIENTE_ID = ISNULL(@CLIENTE_ID, L.CLIENTE_ID)
		AND L.CONTA_BANCARIA_ID = ISNULL(@CONTA_BANCARIA_ID, L.CONTA_BANCARIA_ID)
;
GO
