
IF OBJECT_ID('UP_NOTA_DEBITO_DELETAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_NOTA_DEBITO_DELETAR;
GO

CREATE PROCEDURE UP_NOTA_DEBITO_DELETAR (
	@ID INT
)
AS
SET NOCOUNT ON;

UPDATE NOTA_DEBITO SET ATIVO = 0 WHERE ID = @ID
;
GO
