
IF OBJECT_ID('UP_NOTA_DEBITO_CADASTRAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_NOTA_DEBITO_CADASTRAR;
GO

CREATE PROCEDURE UP_NOTA_DEBITO_CADASTRAR (
	@NOME VARCHAR(20)
    , @DATA_EMISSAO SMALLDATETIME = NULL
    , @DATA_ENVIO SMALLDATETIME = NULL
    , @PREVISAO_PAGAMENTO SMALLDATETIME = NULL
    , @DATA_PAGAMENTO SMALLDATETIME = NULL
    , @OBSERVACAO VARCHAR(4000) = NULL
    , @DATA_REPASSE_REMESSA SMALLDATETIME = NULL
    , @DATA_EMAIL SMALLDATETIME = NULL
    , @EMISSOR_ID INT = NULL
    , @DOLAR_BANCO_CENTRAL MONEY = NULL
)
AS
SET NOCOUNT ON;

IF ISNULL(@NOME, '') <> ''
BEGIN
	INSERT INTO NOTA_DEBITO (
		NOME, DATA_EMISSAO
		, DATA_ENVIO
		, PREVISAO_PAGAMENTO
		, DATA_PAGAMENTO
		, OBSERVACAO
		, DATA_REPASSE_REMESSA
		, DATA_EMAIL
		, EMISSOR_ID
		, DOLAR_BANCO_CENTRAL
	) 
	SELECT	TRIM(@NOME)
			, @DATA_EMISSAO
			, @DATA_ENVIO
			, @PREVISAO_PAGAMENTO
			, @DATA_PAGAMENTO
			, @OBSERVACAO
			, @DATA_REPASSE_REMESSA
			, @DATA_EMAIL
			, @EMISSOR_ID
			, @DOLAR_BANCO_CENTRAL
	;
END
GO
