
IF OBJECT_ID('UP_NOTA_DEBITO_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_NOTA_DEBITO_BUSCAR;
GO

CREATE PROCEDURE UP_NOTA_DEBITO_BUSCAR (
	@ID INT = NULL
	, @NOME VARCHAR(20) = NULL
	, @ATIVO BIT = NULL
    , @DATA_EMISSAO SMALLDATETIME = NULL
    , @DATA_ENVIO SMALLDATETIME = NULL
    , @PREVISAO_PAGAMENTO SMALLDATETIME = NULL
    , @DATA_PAGAMENTO SMALLDATETIME = NULL
    , @OBSERVACAO VARCHAR(4000) = NULL
    , @DATA_REPASSE_REMESSA SMALLDATETIME = NULL
    , @DATA_EMAIL SMALLDATETIME = NULL
    , @DOLAR_BANCO_CENTRAL MONEY = NULL
)
AS
SET NOCOUNT ON;

SELECT	ID AS ID
		, NOME AS NOME
		, ATIVO AS ATIVO
		, DATA_EMISSAO AS DATA_EMISSAO
		, DATA_ENVIO AS DATA_ENVIO
		, PREVISAO_PAGAMENTO AS PREVISAO_PAGAMENTO
		, DATA_PAGAMENTO AS DATA_PAGAMENTO
		, OBSERVACAO AS OBSERVACAO
		, DATA_REPASSE_REMESSA AS DATA_REPASSE_REMESSA
		, DATA_EMAIL AS DATA_EMAIL
		, DOLAR_BANCO_CENTRAL AS DOLAR_BANCO_CENTRAL
FROM	NOTA_DEBITO
WHERE	ID = ISNULL(@ID, ID)
		AND ATIVO = ISNULL(@ATIVO, ATIVO)
		AND NOME = ISNULL(@NOME, NOME)
		AND DATA_EMISSAO = ISNULL(@DATA_EMISSAO, DATA_EMISSAO)
		AND DATA_ENVIO = ISNULL(@DATA_ENVIO, DATA_ENVIO)
		AND PREVISAO_PAGAMENTO = ISNULL(@PREVISAO_PAGAMENTO, PREVISAO_PAGAMENTO)
		AND DATA_PAGAMENTO = ISNULL(@DATA_PAGAMENTO, DATA_PAGAMENTO)
		AND OBSERVACAO = ISNULL(@OBSERVACAO, OBSERVACAO)
		AND DATA_REPASSE_REMESSA = ISNULL(@DATA_REPASSE_REMESSA, DATA_REPASSE_REMESSA)
		AND DATA_EMAIL = ISNULL(@DATA_EMAIL, DATA_EMAIL)
		AND DOLAR_BANCO_CENTRAL = ISNULL(@DOLAR_BANCO_CENTRAL, DOLAR_BANCO_CENTRAL)
;
GO
