
IF OBJECT_ID('UP_NOTA_DEBITO_ATUALIZAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_NOTA_DEBITO_ATUALIZAR;
GO

CREATE PROCEDURE UP_NOTA_DEBITO_ATUALIZAR (
	@ID INT
	, @NOME VARCHAR(20) = NULL
    , @DATA_EMISSAO SMALLDATETIME = NULL
    , @DATA_ENVIO SMALLDATETIME = NULL
    , @PREVISAO_PAGAMENTO SMALLDATETIME = NULL
    , @DATA_PAGAMENTO SMALLDATETIME = NULL
    , @OBSERVACAO VARCHAR(4000) = NULL
    , @DATA_REPASSE_REMESSA SMALLDATETIME = NULL
    , @DATA_EMAIL SMALLDATETIME = NULL
    , @DOLAR_BANCO_CENTRAL MONEY = NULL
)
AS
SET NOCOUNT ON;

UPDATE	NOTA_DEBITO
SET		NOME = ISNULL(NULLIF(@NOME, ''), NOME)
		, DATA_EMISSAO = ISNULL(@DATA_EMISSAO, DATA_EMISSAO)
		, DATA_ENVIO = ISNULL(@DATA_ENVIO, DATA_ENVIO)
		, PREVISAO_PAGAMENTO = ISNULL(@PREVISAO_PAGAMENTO, PREVISAO_PAGAMENTO)
		, DATA_PAGAMENTO = ISNULL(@DATA_PAGAMENTO, DATA_PAGAMENTO)
		, OBSERVACAO = ISNULL(@OBSERVACAO, OBSERVACAO)
		, DATA_REPASSE_REMESSA = ISNULL(@DATA_REPASSE_REMESSA, DATA_REPASSE_REMESSA)
		, DATA_EMAIL = ISNULL(@DATA_EMAIL, DATA_EMAIL)
		, DOLAR_BANCO_CENTRAL = ISNULL(@DOLAR_BANCO_CENTRAL, DOLAR_BANCO_CENTRAL)
WHERE	ID = @ID
;
GO
