
IF OBJECT_ID('UP_PATROCINIO_CADASTRAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_PATROCINIO_CADASTRAR;
GO

CREATE PROCEDURE UP_PATROCINIO_CADASTRAR (
	@SEGURADORA_ID INT
	, @REPRESENTANTE_ID INT
)
AS
SET NOCOUNT ON;

INSERT	INTO PATROCINIO (SEGURADORA_ID, REPRESENTANTE_ID)
SELECT	@SEGURADORA_ID, @REPRESENTANTE_ID
;
GO
