
IF OBJECT_ID('UP_PATROCINIO_ATUALIZAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_PATROCINIO_ATUALIZAR;
GO

CREATE PROCEDURE UP_PATROCINIO_ATUALIZAR (
	@ID INT
	, @SEGURADORA_ID INT = NULL
	, @REPRESENTANTE_ID INT = NULL
)
AS
SET NOCOUNT ON;

UPDATE	PATROCINIO
SET		SEGURADORA_ID = ISNULL(NULLIF(@SEGURADORA_ID, 0), SEGURADORA_ID)
		, REPRESENTANTE_ID = ISNULL(NULLIF(@REPRESENTANTE_ID, 0), REPRESENTANTE_ID)
WHERE	ID = @ID
;
GO
