
IF OBJECT_ID('UP_PATROCINIO_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_PATROCINIO_BUSCAR;
GO

CREATE PROCEDURE UP_PATROCINIO_BUSCAR (
	@ID INT = NULL
	, @SEGURADORA_ID INT = NULL
	, @REPRESENTANTE_ID INT = NULL
)
AS
SET NOCOUNT ON;

SELECT	P.ID AS ID
		, S.ID AS SEGURADORA_ID
		, S.NOME AS SEGURADORA_NOME
		, dbo.UF_FORMATAR_CPF_CNPJ(S.CNPJ) AS SEGURADORA_CNPJ
		, R.ID AS REPRESENTANTE_ID
		, R.NOME AS REPRESENTANTE_NOME
		, dbo.UF_FORMATAR_CPF_CNPJ(R.CNPJ) AS REPRESENTANTE_CNPJ
FROM	PATROCINIO P
INNER	JOIN SEGURADORA S
		ON P.SEGURADORA_ID = S.ID
		AND S.ID = ISNULL(@SEGURADORA_ID, S.ID)
INNER	JOIN REPRESENTANTE R
		ON R.ID = P.REPRESENTANTE_ID
		AND R.ID = ISNULL(@REPRESENTANTE_ID, R.ID)
WHERE	P.ID = ISNULL(@ID, P.ID)
;
GO
