IF OBJECT_ID('imp.UP_REGISTRO_ATUALIZAR', 'P') IS NOT NULL
	DROP PROCEDURE imp.UP_REGISTRO_ATUALIZAR
GO

CREATE PROCEDURE imp.UP_REGISTRO_ATUALIZAR (
		@ID INT
		, @IMPORTACAO_ID INT = NULL
		, @NUMERO_SINISTRO VARCHAR(25) = NULL
		, @CIA VARCHAR(50) = NULL
		, @PROCESSO VARCHAR(50) = NULL
		, @BILHETE VARCHAR(25) = NULL
		, @DATA_EMISSAO_VOUCHER DATE = NULL
		, @REFERENCIA VARCHAR(20) = NULL
		, @DATA_ATENDIMENTO DATE = NULL
		, @DATA_OCORRENCIA DATE = NULL
		, @NOME_SEGURADO VARCHAR(100) = NULL
		, @DOCUMENTO VARCHAR(14) = NULL
		, @VOUCHER VARCHAR(50) = NULL
		, @COBERTURA_RECLAMADA VARCHAR(200) = NULL
		, @CUSTO_ORIGINAL MONEY = NULL
		, @TIPO_MOEDA VARCHAR(3) = NULL
		, @VALOR_FINAL MONEY = NULL
		, @FEE MONEY = NULL
		, @TIPO_MOEDA_FEE VARCHAR(3) = NULL
		, @VALOR_ND_US MONEY = NULL
		, @VALOR_ND_RS MONEY = NULL
		, @TAXA_CAMBIO FLOAT = NULL
		, @SINISTRO_ID INT = NULL
)
AS
SET NOCOUNT ON;

UPDATE	imp.REGISTRO
SET		SINISTRO_ID = @SINISTRO_ID
WHERE	ID = @ID
;
GO