
IF OBJECT_ID('UP_REGISTRO_IMPORTACAO_DELETAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_REGISTRO_IMPORTACAO_DELETAR;
GO

CREATE PROCEDURE UP_REGISTRO_IMPORTACAO_DELETAR (
	@IMPORTACAO_ID INT
)
AS
SET NOCOUNT ON;

UPDATE REGISTRO SET ATIVO = 0 WHERE IMPORTACAO_ID = @IMPORTACAO_ID
;
GO
