
IF OBJECT_ID('UP_REPRESENTANTE_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_REPRESENTANTE_BUSCAR;
GO

CREATE PROCEDURE UP_REPRESENTANTE_BUSCAR (
	@NOME VARCHAR(100)
	, @CNPJ VARCHAR(14)
	, @APENAS_ATIVO BIT = 1
)
AS
SET NOCOUNT ON;

SELECT	R.NOME AS NOME
		, R.CNPJ AS CNPJ
FROM	REPRESENTANTE R
WHERE	R.BIT_ATIVO = ISNULL(@APENAS_ATIVO, R.BIT_ATIVO)
;
GO
