IF OBJECT_ID('imp.UP_REGISTRO_DELETAR', 'P') IS NOT NULL
	DROP PROCEDURE imp.UP_REGISTRO_DELETAR
GO

CREATE PROCEDURE imp.UP_REGISTRO_DELETAR (
	@ID INT
)
AS
SET NOCOUNT ON;

DELETE FROM imp.REGISTRO WHERE ID = @ID;
GO