
IF OBJECT_ID('UP_REPRESENTANTE_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_REPRESENTANTE_BUSCAR;
GO

CREATE PROCEDURE UP_REPRESENTANTE_BUSCAR (
	@ID INT  = NULL
	, @NOME VARCHAR(100) = NULL
	, @CNPJ VARCHAR(14) = NULL
	, @ATIVO BIT = NULL
)
AS
SET NOCOUNT ON;

SELECT	R.ID AS ID
		, R.NOME AS NOME
		, R.CNPJ AS CNPJ
		, R.ATIVO AS ATIVO
		, R.DATA_CRIACAO AS DATA_CRIACAO
		, FORMAT(R.DATA_CRIACAO, 'dd/MM/yyyy hh:mm:ss') AS DATA_ABREVIADA
FROM	REPRESENTANTE R
WHERE	R.ID = ISNULL(@ID, R.ID)
		AND R.ATIVO = ISNULL(@ATIVO, R.ATIVO)
		AND R.NOME = ISNULL(@NOME, R.NOME)
		AND R.CNPJ = ISNULL(@CNPJ, R.CNPJ)
;
GO
