IF OBJECT_ID('imp.UP_REGISTRO_CADASTRAR', 'P') IS NOT NULL
	DROP PROCEDURE imp.UP_REGISTRO_CADASTRAR
GO

CREATE PROCEDURE imp.UP_REGISTRO_CADASTRAR (
		@IMPORTACAO_ID INT
		, @NUMERO_SINISTRO VARCHAR(25) = NULL
		, @COMPANHIA VARCHAR(50) = NULL
		, @PROCESSO VARCHAR(50) = NULL
		, @BILHETE VARCHAR(25) = NULL
		, @DATA_EMISSAO_VOUCHER DATE = NULL
		, @REFERENCIA VARCHAR(20) = NULL
		, @DATA_ATENDIMENTO DATE = NULL
		, @DATA_OCORRENCIA DATE = NULL
		, @NOME_SEGURADO VARCHAR(100) = NULL
		, @DOCUMENTO VARCHAR(14) = NULL
		, @VOUCHER VARCHAR(50) = NULL
		, @COBERTURA_RECLAMADA VARCHAR(200) = NULL
		, @NOME_BANCO VARCHAR(100) = NULL
		, @NUMERO_AGENCIA VARCHAR(4) = NULL
		, @DIGITO_AGENCIA VARCHAR(1) = NULL
		, @NUMERO_CONTA VARCHAR(10) = NULL
		, @DIGITO_CONTA VARCHAR(1) = NULL
		, @EMAIL_CONTATO VARCHAR(100) = NULL
		, @CUSTO_ORIGINAL MONEY = NULL
		, @TIPO_MOEDA VARCHAR(3) = NULL
		, @VALOR_FINAL MONEY = NULL
		, @FEE MONEY = NULL
		, @TIPO_MOEDA_FEE VARCHAR(3) = NULL
		, @VALOR_ND_US MONEY = NULL
		, @VALOR_ND_RS MONEY = NULL
		, @TAXA_CAMBIO FLOAT = NULL
		, @NOTA_DEBITO VARCHAR(20) = NULL
		, @DATA_EMISSAO_ND SMALLDATETIME = NULL
		, @DATA_ENVIO SMALLDATETIME = NULL
		, @STATUS_PAGAMENTO VARCHAR(20) = NULL
)
AS
SET NOCOUNT ON;

IF ISNULL(@IMPORTACAO_ID, 0) <> 0
BEGIN
	INSERT INTO imp.REGISTRO (
		IMPORTACAO_ID, NUMERO_SINISTRO, CIA , PROCESSO , BILHETE , DATA_EMISSAO_VOUCHER , REFERENCIA , DATA_ATENDIMENTO 
		, DATA_OCORRENCIA , NOME_SEGURADO , DOCUMENTO , VOUCHER , COBERTURA_RECLAMADA, NOME_BANCO, NUMERO_AGENCIA
		, DIGITO_AGENCIA, NUMERO_CONTA, DIGITO_CONTA, EMAIL_CONTATO , CUSTO_ORIGINAL , TIPO_MOEDA , VALOR_FINAL 
		, FEE , TIPO_MOEDA_FEE , VALOR_ND_US, VALOR_ND_RS, TAXA_CAMBIO, NOTA_DEBITO, DATA_EMISSAO_ND, DATA_ENVIO, STATUS_PAGAMENTO
	)
	SELECT	@IMPORTACAO_ID, @NUMERO_SINISTRO, @COMPANHIA , @PROCESSO , @BILHETE , @DATA_EMISSAO_VOUCHER , @REFERENCIA , @DATA_ATENDIMENTO 
			, @DATA_OCORRENCIA , @NOME_SEGURADO , @DOCUMENTO , @VOUCHER , @COBERTURA_RECLAMADA , @NOME_BANCO, @NUMERO_AGENCIA
			, @DIGITO_AGENCIA, @NUMERO_CONTA, @DIGITO_CONTA, @EMAIL_CONTATO, @CUSTO_ORIGINAL , @TIPO_MOEDA , @VALOR_FINAL , @FEE 
			, @TIPO_MOEDA_FEE , @VALOR_ND_US, @VALOR_ND_RS, @TAXA_CAMBIO, @NOTA_DEBITO, @DATA_EMISSAO_ND, @DATA_ENVIO, @STATUS_PAGAMENTO
	;
END
GO