IF OBJECT_ID('imp.UP_REGISTRO_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE imp.UP_REGISTRO_BUSCAR
GO

CREATE PROCEDURE imp.UP_REGISTRO_BUSCAR (
		@ID INT = NULL
		, @IMPORTACAO_ID INT = NULL
		, @NUMERO_SINISTRO VARCHAR(25) = NULL
		, @CIA VARCHAR(50) = NULL
		, @PROCESSO VARCHAR(50) = NULL
		, @BILHETE VARCHAR(25) = NULL
		, @DATA_EMISSAO_VOUCHER DATE = NULL
		, @REFERENCIA VARCHAR(20) = NULL
		, @DATA_ATENDIMENTO DATE = NULL
		, @DATA_OCORRENCIA DATE = NULL
		, @NOME_SEGURADO VARCHAR(100) = NULL
		, @DOCUMENTO VARCHAR(14) = NULL
		, @VOUCHER VARCHAR(50) = NULL
		, @COBERTURA_RECLAMADA VARCHAR(200) = NULL
		, @CUSTO_ORIGINAL MONEY = NULL
		, @TIPO_MOEDA VARCHAR(3) = NULL
		, @VALOR_FINAL MONEY = NULL
		, @FEE MONEY = NULL
		, @TIPO_MOEDA_FEE VARCHAR(3) = NULL
		, @VALOR_ND_US MONEY = NULL
		, @VALOR_ND_RS MONEY = NULL
		, @TAXA_CAMBIO FLOAT = NULL
		, @SINISTRO_ID INT = NULL
)
AS
SET NOCOUNT ON;

SELECT	R.ID, R.IMPORTACAO_ID, R.NUMERO_SINISTRO, R.CIA , R.PROCESSO , R.BILHETE , R.DATA_EMISSAO_VOUCHER , R.REFERENCIA , R.DATA_ATENDIMENTO 
		, R.DATA_OCORRENCIA , R.NOME_SEGURADO , R.DOCUMENTO , R.VOUCHER , R.COBERTURA_RECLAMADA, R.NOME_BANCO, R.NUMERO_AGENCIA
		, R.DIGITO_AGENCIA, R.NUMERO_CONTA, R.DIGITO_CONTA, R.EMAIL_CONTATO , R.CUSTO_ORIGINAL , R.TIPO_MOEDA , R.VALOR_FINAL 
		, R.FEE , R.TIPO_MOEDA_FEE , R.VALOR_ND_US, R.VALOR_ND_RS, R.TAXA_CAMBIO
FROM	imp.REGISTRO R
WHERE	R.IMPORTACAO_ID = ISNULL(@ID, R.IMPORTACAO_ID)
GO