
IF OBJECT_ID('UP_REPRESENTANTE_ATUALIZAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_REPRESENTANTE_ATUALIZAR;
GO

CREATE PROCEDURE UP_REPRESENTANTE_ATUALIZAR (
	@ID INT
	, @NOME VARCHAR(100) = NULL
	, @CNPJ VARCHAR(14) = NULL
)
AS
SET NOCOUNT ON;

IF @ID <> 0
BEGIN
	UPDATE	REPRESENTANTE
	SET		NOME = ISNULL(NULLIF(TRIM(@NOME), ''), NOME)
			, CNPJ = RIGHT(CONCAT('00000000000000', ISNULL(NULLIF(TRIM(@CNPJ), ''), CNPJ)), 14)
	WHERE	ID = @ID
	;
END
GO
