
IF OBJECT_ID('UP_REPRESENTANTE_ATUALIZAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_REPRESENTANTE_ATUALIZAR;
GO

CREATE PROCEDURE UP_REPRESENTANTE_ATUALIZAR (
	@ID INT
	, @NOME VARCHAR(100) = NULL
	, @CNPJ VARCHAR(14) = NULL
)
AS
SET NOCOUNT ON;

UPDATE	REPRESENTANTE
SET		NOME = ISNULL(NULLIF(LTRIM(RTRIM(@NOME)), ''), NOME)
		, CNPJ = dbo.UF_TAMANHO_CPF_CNPJ(@CNPJ)
WHERE	ID = @ID
;
GO
