
IF OBJECT_ID('UP_REPRESENTANTE_ATUALIZAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_REPRESENTANTE_ATUALIZAR;
GO

CREATE PROCEDURE UP_REPRESENTANTE_ATUALIZAR (
	@ID INT
	, @NOME VARCHAR(100) = NULL
	, @CNPJ VARCHAR(14) = NULL
)
AS
SET NOCOUNT ON;

UPDATE	REPRESENTANTE
SET		NOME = TRIM(ISNULL(NULLIF(@NOME, ''), NOME))
		, CNPJ = RIGHT(CONCAT('00000000000000', ISNULL(NULLIF(@CNPJ, ''), CNPJ)), 14)
WHERE	ID = @ID
;
GO
