
IF OBJECT_ID('UP_REPRESENTANTE_DELETAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_REPRESENTANTE_DELETAR;
GO

CREATE PROCEDURE UP_REPRESENTANTE_DELETAR (
	@ID INT
)
AS
SET NOCOUNT ON;
UPDATE	REPRESENTANTE
SET		ATIVO = 0
WHERE	ID = @ID
;
GO
