
IF OBJECT_ID('UP_REGISTRO_DELETAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_REGISTRO_DELETAR;
GO

CREATE PROCEDURE UP_REGISTRO_DELETAR (
	@ID INT
)
AS
SET NOCOUNT ON;

UPDATE REGISTRO SET ATIVO = 0 WHERE ID = @ID
;
GO
