
IF OBJECT_ID('UP_REPRESENTANTE_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_REPRESENTANTE_BUSCAR;
GO

CREATE PROCEDURE UP_REPRESENTANTE_BUSCAR (
	@ID INT  = NULL
	, @NOME VARCHAR(100) = NULL
	, @CNPJ VARCHAR(14) = NULL
	, @ATIVO BIT = 1
	, @DATA_INICIAL SMALLDATETIME = NULL
	, @DATA_FINAL SMALLDATETIME = NULL
)
AS
SET NOCOUNT ON;
SET @DATA_FINAL = @DATA_FINAL + ' 23:59:59.997';

SELECT	*
INTO	#REPRESENTANTE
FROM	REPRESENTANTE R
WHERE	R.ID = ISNULL(@ID, R.ID)
		AND R.ATIVO = ISNULL(@ATIVO, R.ATIVO)
		AND R.NOME = ISNULL(NULLIF(@NOME, ''), R.NOME)
		AND R.CNPJ = ISNULL(NULLIF(@CNPJ, ''), R.CNPJ)
		AND R.DATA_CRIACAO BETWEEN ISNULL(NULLIF(@DATA_INICIAL, '1900-01-01'), R.DATA_CRIACAO) AND ISNULL(NULLIF(@DATA_FINAL, '1900-01-01'), R.DATA_CRIACAO)
;

SELECT	R.ID AS ID
		, R.NOME AS NOME
		, R.CNPJ AS CNPJ
		, R.ATIVO AS ATIVO
		, R.DATA_CRIACAO AS DATA_CRIACAO
		, CONVERT(VARCHAR, R.DATA_CRIACAO, 103) AS DATA_ABREVIADA
		, CONVERT(VARCHAR, R.DATA_CRIACAO, 108) AS HORA_ABREVIADA
FROM	#REPRESENTANTE R
;

DROP TABLE #REPRESENTANTE;
GO
