
IF OBJECT_ID('UP_REPRESENTANTE_CADASTRAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_REPRESENTANTE_CADASTRAR;
GO

CREATE PROCEDURE UP_REPRESENTANTE_CADASTRAR (
	@NOME VARCHAR(100)
	, @CNPJ VARCHAR(14)
)
AS
SET NOCOUNT ON;

IF (@NOME <> '' AND @CNPJ <> '')
BEGIN
	INSERT	INTO REPRESENTANTE (NOME, CNPJ)
	SELECT	TRIM(@NOME), RIGHT(CONCAT('00000000000000', @CNPJ), 14);
END
GO
