
IF OBJECT_ID('UP_REGISTRO_IMPORTACAO_ATUALIZAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_REGISTRO_IMPORTACAO_ATUALIZAR;
GO

CREATE PROCEDURE UP_REGISTRO_IMPORTACAO_ATUALIZAR (
	@IMPORTACAO_ID INT
	, @NUMERO_SINISTRO VARCHAR(25) = NULL
    , @CIA VARCHAR(50) = NULL
    , @CLIENTE VARCHAR(50) = NULL
    , @PROCESSO VARCHAR(50) = NULL
    , @BILHETE VARCHAR(25) = NULL
    , @VOUCHER VARCHAR(50) = NULL
    , @DATA_EMISSAO_VOUCHER DATE = NULL
    , @INICIO_VIGENCIA DATE = NULL
    , @FIM_VIGENCIA DATE = NULL
    , @REFERENCIA VARCHAR(20) = NULL
    , @DATA_ATENDIMENTO DATE = NULL
    , @DATA_OCORRENCIA DATE = NULL
    , @NOME_SEGURADO VARCHAR(100) = NULL
    , @TIPO_DOCUMENTO VARCHAR(20) = NULL
    , @DOCUMENTO VARCHAR(14) = NULL
    , @NOME_PRODUTO VARCHAR(20) = NULL
    , @CODIGO_PRODUTO VARCHAR(5) = NULL
    , @COBERTURA_RECLAMADA VARCHAR(200) = NULL
    , @CODIGO_COBERTURA VARCHAR(10) = NULL
    , @CAUSA VARCHAR(500) = NULL
    , @CODIGO_CAUSA VARCHAR(10) = NULL
    , @DESCRIÇAO_EVENTO VARCHAR(500) = NULL
    , @TIPO_PEDIDO VARCHAR(20) = NULL
    , @CAPITAL_SEGURADO MONEY = NULL
    , @VALOR_MOEDA_ORIGINAL MONEY = NULL
    , @TIPO_MOEDA VARCHAR(3) = NULL
    , @VALOR_FATURA_US MONEY = NULL
    , @DESCONTO_US MONEY = NULL
    , @TAXAS_DESCONTO MONEY = NULL
    , @VALOR_FINAL_US MONEY = NULL
    , @FEE MONEY = NULL
    , @TIPO_MOEDA_FEE VARCHAR(3) = NULL
    , @FEE_BANCARIO_RS MONEY = NULL
    , @FEE_BANCARIO_REEMBOLSO_RS MONEY = NULL
    , @VALOR_ND_US MONEY = NULL
    , @VALOR_ND_RS MONEY = NULL
    , @TAXA_CAMBIO FLOAT = NULL
    , @NUMERO_ND VARCHAR(25) = NULL
    , @DATA_EMISSAO_ND DATE = NULL
    , @DATA_PAGAMENTO_SINISTRO DATE = NULL
    , @STATUS_PGTO VARCHAR(10) = NULL
    , @PRAZO_PAGAMENTO DATE = NULL
    , @NOME_BANCO VARCHAR(100) = NULL
    , @TIPO_CONTA VARCHAR(20) = NULL
    , @NUMERO_AGENCIA VARCHAR(4) = NULL
    , @DIGITO_AGENCIA VARCHAR(1) = NULL
    , @NUMERO_CONTA VARCHAR(10) = NULL
    , @DIGITO_CONTA VARCHAR(1) = NULL
    , @NOME_BENEFICIARIO VARCHAR(100) = NULL
    , @DOCUMENTO_BENEFICIARIO VARCHAR(14) = NULL
    , @EMAIL_CONTATO VARCHAR(100) = NULL
    , @PRATICANDO_ESPORTE VARCHAR(5) = NULL
    , @DATA_ENVIO DATE = NULL
)
AS
SET NOCOUNT ON;

UPDATE	REGISTRO
SET		NUMERO_SINISTRO = ISNULL(@NUMERO_SINISTRO, NUMERO_SINISTRO)
		, CIA = ISNULL(@CIA, CIA)
		, CLIENTE = ISNULL(@CLIENTE, CLIENTE)
		, PROCESSO = ISNULL(@PROCESSO, PROCESSO)
		, BILHETE = ISNULL(@BILHETE, BILHETE)
		, VOUCHER = ISNULL(@VOUCHER, VOUCHER)
		, DATA_EMISSAO_VOUCHER = ISNULL(@DATA_EMISSAO_VOUCHER, DATA_EMISSAO_VOUCHER)
		, INICIO_VIGENCIA = ISNULL(@INICIO_VIGENCIA, INICIO_VIGENCIA)
		, FIM_VIGENCIA = ISNULL(@FIM_VIGENCIA, FIM_VIGENCIA)
		, REFERENCIA = ISNULL(@REFERENCIA, REFERENCIA)
		, DATA_ATENDIMENTO = ISNULL(@DATA_ATENDIMENTO, DATA_ATENDIMENTO)
		, DATA_OCORRENCIA = ISNULL(@DATA_OCORRENCIA, DATA_OCORRENCIA)
		, NOME_SEGURADO = ISNULL(@NOME_SEGURADO, NOME_SEGURADO)
		, TIPO_DOCUMENTO = ISNULL(@TIPO_DOCUMENTO, TIPO_DOCUMENTO)
		, DOCUMENTO = ISNULL(@DOCUMENTO, DOCUMENTO)
		, NOME_PRODUTO = ISNULL(@NOME_PRODUTO, NOME_PRODUTO)
		, CODIGO_PRODUTO = ISNULL(@CODIGO_PRODUTO, CODIGO_PRODUTO)
		, COBERTURA_RECLAMADA = ISNULL(@COBERTURA_RECLAMADA, COBERTURA_RECLAMADA)
		, CODIGO_COBERTURA = ISNULL(@CODIGO_COBERTURA, CODIGO_COBERTURA)
		, CAUSA = ISNULL(@CAUSA, CAUSA)
		, CODIGO_CAUSA = ISNULL(@CODIGO_CAUSA, CODIGO_CAUSA)
		, DESCRIÇAO_EVENTO = ISNULL(@DESCRIÇAO_EVENTO, DESCRIÇAO_EVENTO)
		, TIPO_PEDIDO = ISNULL(@TIPO_PEDIDO, TIPO_PEDIDO)
		, CAPITAL_SEGURADO = ISNULL(@CAPITAL_SEGURADO, CAPITAL_SEGURADO)
		, VALOR_MOEDA_ORIGINAL = ISNULL(@VALOR_MOEDA_ORIGINAL, VALOR_MOEDA_ORIGINAL)
		, TIPO_MOEDA = ISNULL(@TIPO_MOEDA, TIPO_MOEDA)
		, VALOR_FATURA_US = ISNULL(@VALOR_FATURA_US, VALOR_FATURA_US)
		, DESCONTO_US = ISNULL(@DESCONTO_US, DESCONTO_US)
		, TAXAS_DESCONTO = ISNULL(@TAXAS_DESCONTO, TAXAS_DESCONTO)
		, VALOR_FINAL_US = ISNULL(@VALOR_FINAL_US, VALOR_FINAL_US)
		, FEE = ISNULL(@FEE, FEE)
		, TIPO_MOEDA_FEE = ISNULL(@TIPO_MOEDA_FEE, TIPO_MOEDA_FEE)
		, FEE_BANCARIO_RS = ISNULL(@FEE_BANCARIO_RS, FEE_BANCARIO_RS)
		, FEE_BANCARIO_REEMBOLSO_RS = ISNULL(@FEE_BANCARIO_REEMBOLSO_RS, FEE_BANCARIO_REEMBOLSO_RS)
		, VALOR_ND_US = ISNULL(@VALOR_ND_US, VALOR_ND_US)
		, VALOR_ND_RS = ISNULL(@VALOR_ND_RS, VALOR_ND_RS)
		, TAXA_CAMBIO = ISNULL(@TAXA_CAMBIO, TAXA_CAMBIO)
		, NUMERO_ND = ISNULL(@NUMERO_ND, NUMERO_ND)
		, DATA_EMISSAO_ND = ISNULL(@DATA_EMISSAO_ND, DATA_EMISSAO_ND)
		, DATA_PAGAMENTO_SINISTRO = ISNULL(@DATA_PAGAMENTO_SINISTRO, DATA_PAGAMENTO_SINISTRO)
		, STATUS_PGTO = ISNULL(@STATUS_PGTO, STATUS_PGTO)
		, PRAZO_PAGAMENTO = ISNULL(@PRAZO_PAGAMENTO, PRAZO_PAGAMENTO)
		, NOME_BANCO = ISNULL(@NOME_BANCO, NOME_BANCO)
		, TIPO_CONTA = ISNULL(@TIPO_CONTA, TIPO_CONTA)
		, NUMERO_AGENCIA = ISNULL(@NUMERO_AGENCIA, NUMERO_AGENCIA)
		, DIGITO_AGENCIA = ISNULL(@DIGITO_AGENCIA, DIGITO_AGENCIA)
		, NUMERO_CONTA = ISNULL(@NUMERO_CONTA, NUMERO_CONTA)
		, DIGITO_CONTA = ISNULL(@DIGITO_CONTA, DIGITO_CONTA)
		, NOME_BENEFICIARIO = ISNULL(@NOME_BENEFICIARIO, NOME_BENEFICIARIO)
		, DOCUMENTO_BENEFICIARIO = ISNULL(@DOCUMENTO_BENEFICIARIO, DOCUMENTO_BENEFICIARIO)
		, EMAIL_CONTATO = ISNULL(@EMAIL_CONTATO, EMAIL_CONTATO)
		, PRATICANDO_ESPORTE = ISNULL(@PRATICANDO_ESPORTE, PRATICANDO_ESPORTE)
		, DATA_ENVIO = ISNULL(@DATA_ENVIO, DATA_ENVIO)
WHERE	IMPORTACAO_ID = @IMPORTACAO_ID
;
GO
