
IF OBJECT_ID('UP_REGISTRO_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_REGISTRO_BUSCAR;
GO

CREATE PROCEDURE UP_REGISTRO_BUSCAR (
	@ID INT = NULL
	, @IMPORTACAO_ID INT = NULL
	, @ATIVO BIT = 1
	, @NUMERO_SINISTRO VARCHAR(25) = NULL
    , @CIA VARCHAR(50) = NULL
    , @CLIENTE VARCHAR(50) = NULL
    , @PROCESSO VARCHAR(50) = NULL
    , @BILHETE VARCHAR(25) = NULL
    , @VOUCHER VARCHAR(50) = NULL
    , @DATA_EMISSAO_VOUCHER DATE = NULL
    , @INICIO_VIGENCIA DATE = NULL
    , @FIM_VIGENCIA DATE = NULL
    , @REFERENCIA VARCHAR(20) = NULL
    , @DATA_ATENDIMENTO DATE = NULL
    , @DATA_OCORRENCIA DATE = NULL
    , @NOME_SEGURADO VARCHAR(100) = NULL
    , @TIPO_DOCUMENTO VARCHAR(20) = NULL
    , @DOCUMENTO VARCHAR(14) = NULL
    , @NOME_PRODUTO VARCHAR(20) = NULL
    , @CODIGO_PRODUTO VARCHAR(5) = NULL
    , @COBERTURA_RECLAMADA VARCHAR(200) = NULL
    , @CODIGO_COBERTURA VARCHAR(10) = NULL
    , @CAUSA VARCHAR(500) = NULL
    , @CODIGO_CAUSA VARCHAR(10) = NULL
    , @DESCRIÇAO_EVENTO VARCHAR(500) = NULL
    , @TIPO_PEDIDO VARCHAR(20) = NULL
    , @CAPITAL_SEGURADO MONEY = NULL
    , @VALOR_MOEDA_ORIGINAL MONEY = NULL
    , @TIPO_MOEDA VARCHAR(3) = NULL
    , @VALOR_FATURA_US MONEY = NULL
    , @DESCONTO_US MONEY = NULL
    , @TAXAS_DESCONTO MONEY = NULL
    , @VALOR_FINAL_US MONEY = NULL
    , @FEE MONEY = NULL
    , @TIPO_MOEDA_FEE VARCHAR(3) = NULL
    , @FEE_BANCARIO_RS MONEY = NULL
    , @FEE_BANCARIO_REEMBOLSO_RS MONEY = NULL
    , @VALOR_ND_US MONEY = NULL
    , @VALOR_ND_RS MONEY = NULL
    , @TAXA_CAMBIO FLOAT = NULL
    , @NUMERO_ND VARCHAR(25) = NULL
    , @DATA_EMISSAO_ND DATE = NULL
    , @DATA_PAGAMENTO_SINISTRO DATE = NULL
    , @STATUS_PGTO VARCHAR(10) = NULL
    , @PRAZO_PAGAMENTO DATE = NULL
    , @NOME_BANCO VARCHAR(100) = NULL
    , @TIPO_CONTA VARCHAR(20) = NULL
    , @NUMERO_AGENCIA VARCHAR(4) = NULL
    , @DIGITO_AGENCIA VARCHAR(1) = NULL
    , @NUMERO_CONTA VARCHAR(10) = NULL
    , @DIGITO_CONTA VARCHAR(1) = NULL
    , @NOME_BENEFICIARIO VARCHAR(100) = NULL
    , @DOCUMENTO_BENEFICIARIO VARCHAR(14) = NULL
    , @EMAIL_CONTATO VARCHAR(100) = NULL
    , @PRATICANDO_ESPORTE VARCHAR(5) = NULL
    , @DATA_ENVIO DATE = NULL
)
AS
SET NOCOUNT ON;

SELECT	ID AS ID
		, IMPORTACAO_ID AS IMPORTACAO_ID
		, ATIVO AS ATIVO
		, NUMERO_SINISTRO AS NUMERO_SINISTRO
		, CIA AS CIA
		, CLIENTE AS CLIENTE
		, PROCESSO AS PROCESSO
		, BILHETE AS BILHETE
		, VOUCHER AS VOUCHER
		, DATA_EMISSAO_VOUCHER AS DATA_EMISSAO_VOUCHER
		, INICIO_VIGENCIA AS INICIO_VIGENCIA
		, FIM_VIGENCIA AS FIM_VIGENCIA
		, REFERENCIA AS REFERENCIA
		, DATA_ATENDIMENTO AS DATA_ATENDIMENTO
		, DATA_OCORRENCIA AS DATA_OCORRENCIA
		, NOME_SEGURADO AS NOME_SEGURADO
		, TIPO_DOCUMENTO AS TIPO_DOCUMENTO
		, DOCUMENTO AS DOCUMENTO
		, NOME_PRODUTO AS NOME_PRODUTO
		, CODIGO_PRODUTO AS CODIGO_PRODUTO
		, COBERTURA_RECLAMADA AS COBERTURA_RECLAMADA
		, CODIGO_COBERTURA AS CODIGO_COBERTURA
		, CAUSA AS CAUSA
		, CODIGO_CAUSA AS CODIGO_CAUSA
		, DESCRIÇAO_EVENTO AS DESCRIÇAO_EVENTO
		, TIPO_PEDIDO AS TIPO_PEDIDO
		, CAPITAL_SEGURADO AS CAPITAL_SEGURADO
		, VALOR_MOEDA_ORIGINAL AS VALOR_MOEDA_ORIGINAL
		, TIPO_MOEDA AS TIPO_MOEDA
		, VALOR_FATURA_US AS VALOR_FATURA_US
		, DESCONTO_US AS DESCONTO_US
		, TAXAS_DESCONTO AS TAXAS_DESCONTO
		, VALOR_FINAL_US AS VALOR_FINAL_US
		, FEE AS FEE
		, TIPO_MOEDA_FEE AS TIPO_MOEDA_FEE
		, FEE_BANCARIO_RS AS FEE_BANCARIO_RS
		, FEE_BANCARIO_REEMBOLSO_RS AS FEE_BANCARIO_REEMBOLSO_RS
		, VALOR_ND_US AS VALOR_ND_US
		, VALOR_ND_RS AS VALOR_ND_RS
		, TAXA_CAMBIO AS TAXA_CAMBIO
		, NUMERO_ND AS NUMERO_ND
		, DATA_EMISSAO_ND AS DATA_EMISSAO_ND
		, DATA_PAGAMENTO_SINISTRO AS DATA_PAGAMENTO_SINISTRO
		, STATUS_PGTO AS STATUS_PGTO
		, PRAZO_PAGAMENTO AS PRAZO_PAGAMENTO
		, NOME_BANCO AS NOME_BANCO
		, TIPO_CONTA AS TIPO_CONTA
		, NUMERO_AGENCIA AS NUMERO_AGENCIA
		, DIGITO_AGENCIA AS DIGITO_AGENCIA
		, NUMERO_CONTA AS NUMERO_CONTA
		, DIGITO_CONTA AS DIGITO_CONTA
		, NOME_BENEFICIARIO AS NOME_BENEFICIARIO
		, DOCUMENTO_BENEFICIARIO AS DOCUMENTO_BENEFICIARIO
		, EMAIL_CONTATO AS EMAIL_CONTATO
		, PRATICANDO_ESPORTE AS PRATICANDO_ESPORTE
		, DATA_ENVIO AS DATA_ENVIO
FROM	REGISTRO
WHERE	ID = ISNULL(NULLIF(@ID, 0), ID)
		AND IMPORTACAO_ID = ISNULL(@IMPORTACAO_ID, IMPORTACAO_ID)
		AND ATIVO = ISNULL(@ATIVO, ATIVO)
		AND NUMERO_SINISTRO = ISNULL(@NUMERO_SINISTRO, NUMERO_SINISTRO)
		AND CIA = ISNULL(@CIA, CIA)
		AND CLIENTE = ISNULL(@CLIENTE, CLIENTE)
		AND PROCESSO = ISNULL(@PROCESSO, PROCESSO)
		AND BILHETE = ISNULL(@BILHETE, BILHETE)
		AND VOUCHER = ISNULL(@VOUCHER, VOUCHER)
		AND DATA_EMISSAO_VOUCHER = ISNULL(@DATA_EMISSAO_VOUCHER, DATA_EMISSAO_VOUCHER)
		AND INICIO_VIGENCIA = ISNULL(@INICIO_VIGENCIA, INICIO_VIGENCIA)
		AND FIM_VIGENCIA = ISNULL(@FIM_VIGENCIA, FIM_VIGENCIA)
		AND REFERENCIA = ISNULL(@REFERENCIA, REFERENCIA)
		AND DATA_ATENDIMENTO = ISNULL(@DATA_ATENDIMENTO, DATA_ATENDIMENTO)
		AND DATA_OCORRENCIA = ISNULL(@DATA_OCORRENCIA, DATA_OCORRENCIA)
		AND NOME_SEGURADO = ISNULL(@NOME_SEGURADO, NOME_SEGURADO)
		AND TIPO_DOCUMENTO = ISNULL(@TIPO_DOCUMENTO, TIPO_DOCUMENTO)
		AND DOCUMENTO = ISNULL(@DOCUMENTO, DOCUMENTO)
		AND NOME_PRODUTO = ISNULL(@NOME_PRODUTO, NOME_PRODUTO)
		AND CODIGO_PRODUTO = ISNULL(@CODIGO_PRODUTO, CODIGO_PRODUTO)
		AND COBERTURA_RECLAMADA = ISNULL(@COBERTURA_RECLAMADA, COBERTURA_RECLAMADA)
		AND CODIGO_COBERTURA = ISNULL(@CODIGO_COBERTURA, CODIGO_COBERTURA)
		AND CAUSA = ISNULL(@CAUSA, CAUSA)
		AND CODIGO_CAUSA = ISNULL(@CODIGO_CAUSA, CODIGO_CAUSA)
		AND DESCRIÇAO_EVENTO = ISNULL(@DESCRIÇAO_EVENTO, DESCRIÇAO_EVENTO)
		AND TIPO_PEDIDO = ISNULL(@TIPO_PEDIDO, TIPO_PEDIDO)
		AND CAPITAL_SEGURADO = ISNULL(@CAPITAL_SEGURADO, CAPITAL_SEGURADO)
		AND VALOR_MOEDA_ORIGINAL = ISNULL(@VALOR_MOEDA_ORIGINAL, VALOR_MOEDA_ORIGINAL)
		AND TIPO_MOEDA = ISNULL(@TIPO_MOEDA, TIPO_MOEDA)
		AND VALOR_FATURA_US = ISNULL(@VALOR_FATURA_US, VALOR_FATURA_US)
		AND DESCONTO_US = ISNULL(@DESCONTO_US, DESCONTO_US)
		AND TAXAS_DESCONTO = ISNULL(@TAXAS_DESCONTO, TAXAS_DESCONTO)
		AND VALOR_FINAL_US = ISNULL(@VALOR_FINAL_US, VALOR_FINAL_US)
		AND FEE = ISNULL(@FEE, FEE)
		AND TIPO_MOEDA_FEE = ISNULL(@TIPO_MOEDA_FEE, TIPO_MOEDA_FEE)
		AND FEE_BANCARIO_RS = ISNULL(@FEE_BANCARIO_RS, FEE_BANCARIO_RS)
		AND FEE_BANCARIO_REEMBOLSO_RS = ISNULL(@FEE_BANCARIO_REEMBOLSO_RS, FEE_BANCARIO_REEMBOLSO_RS)
		AND VALOR_ND_US = ISNULL(@VALOR_ND_US, VALOR_ND_US)
		AND VALOR_ND_RS = ISNULL(@VALOR_ND_RS, VALOR_ND_RS)
		AND TAXA_CAMBIO = ISNULL(@TAXA_CAMBIO, TAXA_CAMBIO)
		AND NUMERO_ND = ISNULL(@NUMERO_ND, NUMERO_ND)
		AND DATA_EMISSAO_ND = ISNULL(@DATA_EMISSAO_ND, DATA_EMISSAO_ND)
		AND DATA_PAGAMENTO_SINISTRO = ISNULL(@DATA_PAGAMENTO_SINISTRO, DATA_PAGAMENTO_SINISTRO)
		AND STATUS_PGTO = ISNULL(@STATUS_PGTO, STATUS_PGTO)
		AND PRAZO_PAGAMENTO = ISNULL(@PRAZO_PAGAMENTO, PRAZO_PAGAMENTO)
		AND NOME_BANCO = ISNULL(@NOME_BANCO, NOME_BANCO)
		AND TIPO_CONTA = ISNULL(@TIPO_CONTA, TIPO_CONTA)
		AND NUMERO_AGENCIA = ISNULL(@NUMERO_AGENCIA, NUMERO_AGENCIA)
		AND DIGITO_AGENCIA = ISNULL(@DIGITO_AGENCIA, DIGITO_AGENCIA)
		AND NUMERO_CONTA = ISNULL(@NUMERO_CONTA, NUMERO_CONTA)
		AND DIGITO_CONTA = ISNULL(@DIGITO_CONTA, DIGITO_CONTA)
		AND NOME_BENEFICIARIO = ISNULL(@NOME_BENEFICIARIO, NOME_BENEFICIARIO)
		AND DOCUMENTO_BENEFICIARIO = ISNULL(@DOCUMENTO_BENEFICIARIO, DOCUMENTO_BENEFICIARIO)
		AND EMAIL_CONTATO = ISNULL(@EMAIL_CONTATO, EMAIL_CONTATO)
		AND PRATICANDO_ESPORTE = ISNULL(@PRATICANDO_ESPORTE, PRATICANDO_ESPORTE)
		AND DATA_ENVIO = ISNULL(@DATA_ENVIO, DATA_ENVIO)
;
GO
