
IF OBJECT_ID('UP_SITUACAO_SINISTRO_ATUALIZAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_SITUACAO_SINISTRO_ATUALIZAR;
GO

CREATE PROCEDURE UP_SITUACAO_SINISTRO_ATUALIZAR (
	@ID INT
	, @NOME VARCHAR(100) = NULL
)
AS
SET NOCOUNT ON;

UPDATE	SITUACAO_SINISTRO
SET		NOME = ISNULL(NULLIF(@NOME, ''), NOME)
WHERE	ID = @ID
;
GO
