
IF OBJECT_ID('UP_SEGURADORA_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_SEGURADORA_BUSCAR;
GO

CREATE PROCEDURE UP_SEGURADORA_BUSCAR (
	@ID INT = NULL
	, @APENAS_ATIVO BIT = 1
)
AS
SET NOCOUNT ON;

SELECT	S.ID AS ID
		, S.NOME AS SEGURADORA
		, dbo.UF_FORMATAR_CPF_CNPJ(S.CNPJ) AS CNPJ
		, S.DATA_CRIACAO AS DATA_CRIACAO
		, S.BIT_ATIVO AS ATIVO
		, CONVERT(VARCHAR, S.DATA_CRIACAO, 103) AS DATA_ABREVIADA
		, CONVERT(VARCHAR, S.DATA_CRIACAO, 108) AS HORA_ABREVIADA
FROM	SEGURADORA S
WHERE	S.ID = ISNULL(NULLIF(@ID, 0), S.ID)
		AND S.BIT_ATIVO = ISNULL(@APENAS_ATIVO, S.BIT_ATIVO)
;
GO
