
IF OBJECT_ID('UP_SEGURADORA_CADASTRAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_SEGURADORA_CADASTRAR;
GO

CREATE PROCEDURE UP_SEGURADORA_CADASTRAR (
	@NOME VARCHAR(100)
	, @CNPJ VARCHAR(14)
	, @ANTECIPACAO BIT = 0
)
AS
SET NOCOUNT ON;

IF (@NOME <> '' AND @CNPJ <> '')
BEGIN
	INSERT	INTO SEGURADORA (NOME, CNPJ, ANTECIPACAO)
	OUTPUT	inserted.ID
	SELECT	LTRIM(RTRIM(@NOME)), RIGHT(CONCAT('00000000000000', @CNPJ), 14), ISNULL(@ANTECIPACAO, 0)
	;
END
GO
