
IF OBJECT_ID('UP_SEGURADORA_CADASTRAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_SEGURADORA_CADASTRAR;
GO

CREATE PROCEDURE UP_SEGURADORA_CADASTRAR (
	@NOME VARCHAR(100)
	, @CNPJ VARCHAR(14)
	, @ANTECIPACAO BIT = 0
)
AS
SET NOCOUNT ON;

INSERT	INTO SEGURADORA (NOME, CNPJ, CONTROLA_ANTECIPACAO)
OUTPUT	inserted.ID
SELECT	TRIM(@NOME), RIGHT(CONCAT('00000000000000', @CNPJ), 14), ISNULL(@ANTECIPACAO, 0);
GO
