
IF OBJECT_ID('UP_SINISTRO_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_SINISTRO_BUSCAR;
GO

CREATE PROCEDURE UP_SINISTRO_BUSCAR (
	@ID INT = NULL
	, @ATIVO BIT = 1
	, @DATA_RELACAO SMALLDATETIME = NULL
    , @REPRESENTANTE_SEGURADORA_ID INT = NULL
    , @PRAZO_PAGAMENTO SMALLDATETIME = NULL
    , @DATA_OCORRENCIA SMALLDATETIME = NULL
    , @SEGURADO_ID INT = NULL
    , @REFERENCIA VARCHAR(20) = NULL
    , @BILHETE VARCHAR(10) = NULL
    , @VOUCHER VARCHAR(20) = NULL
    , @TIPO_COBERTURA_ID INT = NULL
    , @VALOR_DOLAR MONEY = NULL
    , @VALOR_DOLAR_DESCONTO MONEY = NULL
    , @FEE_DOLAR MONEY = NULL
    , @CAMBIO MONEY = NULL
    , @VALOR_REAL MONEY = NULL
    , @VALOR_REAL_DESCONTO MONEY = NULL
    , @FEE_REAL MONEY = NULL
    , @TRANSFERENCIA_CONTA_INTERNA BIT = NULL
    , @DATA_PAGAMENTO SMALLDATETIME = NULL
    , @DOC_DEVOLVIDO BIT = NULL
    , @DOC_DEVOLVIDO_DESC VARCHAR(4000) = NULL
    , @OBSERVACAO VARCHAR(4000) = NULL
    , @DATA_RECEBIMENTO SMALLDATETIME = NULL
    , @NOTA_DEBITO_ID INT = NULL
    , @TIPO_MOEDA_ID INT = NULL
    , @REMESSA_DOLAR MONEY = NULL
    , @COMISSAO MONEY = NULL
    , @SITUACAO_SINISTRO_ID INT = NULL
)
AS
SET NOCOUNT ON;

SELECT	ID AS ID
		, ATIVO AS ATIVO
		, DATA_RELACAO AS DATA_RELACAO
		, REPRESENTANTE_SEGURADORA_ID AS REPRESENTANTE_SEGURADORA_ID
		, PRAZO_PAGAMENTO AS PRAZO_PAGAMENTO
		, DATA_OCORRENCIA AS DATA_OCORRENCIA
		, SEGURADO_ID AS SEGURADO_ID
		, REFERENCIA AS REFERENCIA
		, BILHETE AS BILHETE
		, VOUCHER AS VOUCHER
		, TIPO_COBERTURA_ID AS TIPO_COBERTURA_ID
		, VALOR_DOLAR AS VALOR_DOLAR
		, VALOR_DOLAR_DESCONTO AS VALOR_DOLAR_DESCONTO
		, FEE_DOLAR AS FEE_DOLAR
		, CAMBIO AS CAMBIO
		, VALOR_REAL AS VALOR_REAL
		, VALOR_REAL_DESCONTO AS VALOR_REAL_DESCONTO
		, FEE_REAL AS FEE_REAL
		, TRANSFERENCIA_CONTA_INTERNA AS TRANSFERENCIA_CONTA_INTERNA
		, DATA_PAGAMENTO AS DATA_PAGAMENTO
		, DOC_DEVOLVIDO AS DOC_DEVOLVIDO
		, DOC_DEVOLVIDO_DESC AS DOC_DEVOLVIDO_DESC
		, OBSERVACAO AS OBSERVACAO
		, DATA_RECEBIMENTO AS DATA_RECEBIMENTO
		, NOTA_DEBITO_ID AS NOTA_DEBITO_ID
		, TIPO_MOEDA_ID AS TIPO_MOEDA_ID
		, REMESSA_DOLAR AS REMESSA_DOLAR
		, COMISSAO AS COMISSAO
		, SITUACAO_SINISTRO_ID AS SITUACAO_SINISTRO_ID
FROM	SINISTRO
WHERE	ID = ISNULL(NULLIF(@ID, 0), ID)
		AND ATIVO = ISNULL(@ATIVO, ATIVO)
		AND DATA_RELACAO = ISNULL(@DATA_RELACAO, DATA_RELACAO)
		AND REPRESENTANTE_SEGURADORA_ID = ISNULL(@REPRESENTANTE_SEGURADORA_ID, REPRESENTANTE_SEGURADORA_ID)
		AND PRAZO_PAGAMENTO = ISNULL(@PRAZO_PAGAMENTO, PRAZO_PAGAMENTO)
		AND DATA_OCORRENCIA = ISNULL(@DATA_OCORRENCIA, DATA_OCORRENCIA)
		AND SEGURADO_ID = ISNULL(@SEGURADO_ID, SEGURADO_ID)
		AND REFERENCIA = ISNULL(@REFERENCIA, REFERENCIA)
		AND BILHETE = ISNULL(@BILHETE, BILHETE)
		AND VOUCHER = ISNULL(@VOUCHER, VOUCHER)
		AND TIPO_COBERTURA_ID = ISNULL(@TIPO_COBERTURA_ID, TIPO_COBERTURA_ID)
		AND VALOR_DOLAR = ISNULL(@VALOR_DOLAR, VALOR_DOLAR)
		AND VALOR_DOLAR_DESCONTO = ISNULL(@VALOR_DOLAR_DESCONTO, VALOR_DOLAR_DESCONTO)
		AND FEE_DOLAR = ISNULL(@FEE_DOLAR, FEE_DOLAR)
		AND CAMBIO = ISNULL(@CAMBIO, CAMBIO)
		AND VALOR_REAL = ISNULL(@VALOR_REAL, VALOR_REAL)
		AND VALOR_REAL_DESCONTO = ISNULL(@VALOR_REAL_DESCONTO, VALOR_REAL_DESCONTO)
		AND FEE_REAL = ISNULL(@FEE_REAL, FEE_REAL)
		AND TRANSFERENCIA_CONTA_INTERNA = ISNULL(@TRANSFERENCIA_CONTA_INTERNA, TRANSFERENCIA_CONTA_INTERNA)
		AND DATA_PAGAMENTO = ISNULL(@DATA_PAGAMENTO, DATA_PAGAMENTO)
		AND DOC_DEVOLVIDO = ISNULL(@DOC_DEVOLVIDO, DOC_DEVOLVIDO)
		AND DOC_DEVOLVIDO_DESC = ISNULL(@DOC_DEVOLVIDO_DESC, DOC_DEVOLVIDO_DESC)
		AND OBSERVACAO = ISNULL(@OBSERVACAO, OBSERVACAO)
		AND DATA_RECEBIMENTO = ISNULL(@DATA_RECEBIMENTO, DATA_RECEBIMENTO)
		AND NOTA_DEBITO_ID = ISNULL(@NOTA_DEBITO_ID, NOTA_DEBITO_ID)
		AND TIPO_MOEDA_ID = ISNULL(@TIPO_MOEDA_ID, TIPO_MOEDA_ID)
		AND REMESSA_DOLAR = ISNULL(@REMESSA_DOLAR, REMESSA_DOLAR)
		AND COMISSAO = ISNULL(@COMISSAO, COMISSAO)
		AND SITUACAO_SINISTRO_ID = ISNULL(@SITUACAO_SINISTRO_ID, SITUACAO_SINISTRO_ID)
;
GO
