
IF OBJECT_ID('UP_SEGURADO_ATUALIZAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_SEGURADO_ATUALIZAR;
GO

CREATE PROCEDURE UP_SEGURADO_ATUALIZAR (
	@ID INT
	, @NOME VARCHAR(100) = NULL
	, @CPF VARCHAR(14) = NULL
	, @BANCO VARCHAR(100) = NULL
	, @AGENCIA VARCHAR(4) = NULL
	, @DIGITO_AGENCIA CHAR = NULL
	, @CONTA VARCHAR(10) = NULL
	, @DIGITO_CONTA CHAR = NULL
	, @BENEFICIARIO VARCHAR(100) = NULL
	, @CPF_BENEFICIARIO VARCHAR(14) = NULL
	, @EMAIL VARCHAR(100) = NULL
	, @CONTA_CADASTRADA BIT = NULL
)
AS
SET NOCOUNT ON;

UPDATE	SEGURADO
SET		NOME = ISNULL(NULLIF(@NOME, ''), NOME)
		, CPF = dbo.UF_TAMANHO_CPF_CNPJ(ISNULL(@CPF, ''))
		, BANCO = ISNULL(@BANCO, BANCO)
		, AGENCIA = ISNULL(@AGENCIA, AGENCIA)
		, DIGITO_AGENCIA = ISNULL(@DIGITO_AGENCIA, DIGITO_AGENCIA)
		, CONTA = ISNULL(@CONTA, CONTA)
		, DIGITO_CONTA = ISNULL(@DIGITO_CONTA, DIGITO_CONTA)
		, BENEFICIARIO = ISNULL(@BENEFICIARIO, BENEFICIARIO)
		, CPF_BENEFICIARIO = dbo.UF_TAMANHO_CPF_CNPJ(ISNULL(@CPF_BENEFICIARIO, CPF_BENEFICIARIO))
		, EMAIL = ISNULL(@EMAIL, EMAIL)
		, CONTA_CADASTRADA = ISNULL(@CONTA_CADASTRADA, CONTA_CADASTRADA)
WHERE	ID = @ID
;
GO
