
IF OBJECT_ID('UP_SITUACAO_SINISTRO_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_SITUACAO_SINISTRO_BUSCAR;
GO

CREATE PROCEDURE UP_SITUACAO_SINISTRO_BUSCAR (
	@ID INT = NULL
	, @NOME VARCHAR(100) = NULL
	, @ATIVO BIT = 1
)
AS
SET NOCOUNT ON;

SELECT	S.ID AS ID
		, S.NOME AS NOME
		, S.ATIVO AS ATIVO
FROM	SITUACAO_SINISTRO S
WHERE	S.ID = ISNULL(NULLIF(@ID, 0), S.ID)
		AND S.ATIVO = ISNULL(@ATIVO, S.ATIVO)
		AND S.NOME = ISNULL(NULLIF(@NOME, ''), S.NOME)
;
GO
