
IF OBJECT_ID('UP_SINISTRO_CADASTRAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_SINISTRO_CADASTRAR;
GO

CREATE PROCEDURE UP_SINISTRO_CADASTRAR (
	@DATA_RELACAO SMALLDATETIME = NULL
    , @REPRESENTANTE_SEGURADORA_ID INT = NULL
    , @PRAZO_PAGAMENTO SMALLDATETIME = NULL
    , @DATA_OCORRENCIA SMALLDATETIME = NULL
    , @SEGURADO_ID INT = NULL
    , @REFERENCIA VARCHAR(20) = NULL
    , @BILHETE VARCHAR(10) = NULL
    , @VOUCHER VARCHAR(20) = NULL
    , @TIPO_COBERTURA_ID INT = NULL
    , @VALOR_DOLAR MONEY = NULL
    , @VALOR_DOLAR_DESCONTO MONEY = NULL
    , @FEE_DOLAR MONEY = NULL
    , @CAMBIO MONEY = NULL
    , @VALOR_REAL MONEY = NULL
    , @VALOR_REAL_DESCONTO MONEY = NULL
    , @FEE_REAL MONEY = NULL
    , @TRANSFERENCIA_CONTA_INTERNA BIT = NULL
    , @DATA_PAGAMENTO SMALLDATETIME = NULL
    , @DOC_DEVOLVIDO BIT = NULL
    , @DOC_DEVOLVIDO_DESC VARCHAR(4000) = NULL
    , @OBSERVACAO VARCHAR(4000) = NULL
    , @DATA_RECEBIMENTO SMALLDATETIME = NULL
    , @NOTA_DEBITO_ID INT = NULL
    , @TIPO_MOEDA_ID INT = NULL
    , @REMESSA_DOLAR MONEY = NULL
    , @COMISSAO MONEY = NULL
    , @SITUACAO_SINISTRO_ID INT = NULL
)
AS
SET NOCOUNT ON;

INSERT INTO SINISTRO (
	DATA_RELACAO
	, REPRESENTANTE_SEGURADORA_ID
	, PRAZO_PAGAMENTO
	, DATA_OCORRENCIA
	, SEGURADO_ID
	, REFERENCIA
	, BILHETE
	, VOUCHER
	, TIPO_COBERTURA_ID
	, VALOR_DOLAR
	, VALOR_DOLAR_DESCONTO
	, FEE_DOLAR
	, CAMBIO
	, VALOR_REAL
	, VALOR_REAL_DESCONTO
	, FEE_REAL
	, TRANSFERENCIA_CONTA_INTERNA
	, DATA_PAGAMENTO
	, DOC_DEVOLVIDO
	, DOC_DEVOLVIDO_DESC
	, OBSERVACAO
	, DATA_RECEBIMENTO
	, NOTA_DEBITO_ID
	, TIPO_MOEDA_ID
	, REMESSA_DOLAR
	, COMISSAO
	, SITUACAO_SINISTRO_ID
) 
SELECT	@DATA_RELACAO
		, @REPRESENTANTE_SEGURADORA_ID
		, @PRAZO_PAGAMENTO
		, @DATA_OCORRENCIA
		, @SEGURADO_ID
		, @REFERENCIA
		, @BILHETE
		, @VOUCHER
		, @TIPO_COBERTURA_ID
		, @VALOR_DOLAR
		, @VALOR_DOLAR_DESCONTO
		, @FEE_DOLAR
		, @CAMBIO
		, @VALOR_REAL
		, @VALOR_REAL_DESCONTO
		, @FEE_REAL
		, @TRANSFERENCIA_CONTA_INTERNA
		, @DATA_PAGAMENTO
		, @DOC_DEVOLVIDO
		, @DOC_DEVOLVIDO_DESC
		, @OBSERVACAO
		, @DATA_RECEBIMENTO
		, @NOTA_DEBITO_ID
		, @TIPO_MOEDA_ID
		, @REMESSA_DOLAR
		, @COMISSAO
		, @SITUACAO_SINISTRO_ID
GO
