
IF OBJECT_ID('UP_SEGURADO_CADASTRAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_SEGURADO_CADASTRAR;
GO

CREATE PROCEDURE UP_SEGURADO_CADASTRAR (
	@NOME VARCHAR(100)
	, @CPF VARCHAR(14)
	, @BANCO VARCHAR(100) = NULL
	, @AGENCIA VARCHAR(4) = NULL
	, @DIGITO_AGENCIA CHAR = NULL
	, @CONTA VARCHAR(10) = NULL
	, @DIGITO_CONTA CHAR = NULL
	, @BENEFICIARIO VARCHAR(100) = NULL
	, @CPF_BENEFICIARIO VARCHAR(14) = NULL
	, @EMAIL VARCHAR(100) = NULL
	, @CONTA_CADASTRADA BIT = NULL
)
AS
SET NOCOUNT ON;

IF (@NOME <> '' AND @CPF <> '')
BEGIN
	INSERT	INTO SEGURADO (
		NOME, CPF, BANCO, AGENCIA, DIGITO_AGENCIA, CONTA, DIGITO_CONTA
		, BENEFICIARIO, CPF_BENEFICIARIO, EMAIL, CONTA_CADASTRADA
	)
	SELECT	@NOME, @CPF, @BANCO, @AGENCIA, @DIGITO_AGENCIA, @CONTA, @DIGITO_CONTA
			, @BENEFICIARIO, @CPF_BENEFICIARIO, @EMAIL, ISNULL(@CONTA_CADASTRADA, 0)
	;
END
GO
