IF OBJECT_ID('UP_SINISTRO_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_SINISTRO_BUSCAR;
GO

CREATE PROCEDURE UP_SINISTRO_BUSCAR (
	@IMPORTACAO_ID INT
)
AS
SET NOCOUNT ON;

SELECT	S.ID, S.NUMERO_SINISTRO, S.PROCESSO, S.BILHETE, S.REFERENCIA, S.DATA_ATENDIMENTO, S.DATA_OCORRENCIA
	, S.VOUCHER, S.COBERTURA, S.CUSTO_ORIGINAL, S.TIPO_MOEDA, S.VALOR_FINAL, S.FEE, S.TIPO_MOEDA_FEE
	, S.VALOR_DOLAR, S.VALOR_REAL, S.DOLAR, ND.NOME AS ND, CLI.NOME AS SEGURADO, SG.NOME AS SEGURADORA, RE.NOME AS REPRESENTANTE
FROM	SINISTRO S
INNER	JOIN imp.REGISTRO R
		ON R.ID = S.REGISTRO_ID
		AND R.IMPORTACAO_ID = @IMPORTACAO_ID
INNER	JOIN NOTA_DEBITO ND
		ON ND.ID = S.NOTA_DEBITO_ID
INNER	JOIN SEGURADO CLI
		ON CLI.ID = S.SEGURADO_ID
INNER	JOIN PATROCINIO P
		ON P.ID = S.PATROCINIO_ID
INNER	JOIN SEGURADORA SG
		ON SG.ID = P.SEGURADORA_ID
INNER	JOIN REPRESENTANTE RE
		ON RE.ID = P.REPRESENTANTE_ID
;
GO