
IF OBJECT_ID('UP_SEGURADORA_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_SEGURADORA_BUSCAR;
GO

CREATE PROCEDURE UP_SEGURADORA_BUSCAR (
	@ID INT = NULL
	, @NOME VARCHAR(100) = NULL
	, @CNPJ VARCHAR(14) = NULL
	, @ATIVO BIT = 1
	, @DATA_INICIAL SMALLDATETIME = NULL
	, @DATA_FINAL SMALLDATETIME = NULL
)
AS
SET NOCOUNT ON;
SET @DATA_FINAL = @DATA_FINAL + ' 23:59:59.997';

SELECT	*
INTO	#SEGURADORA
FROM	SEGURADORA S
WHERE	S.ID = ISNULL(NULLIF(@ID, 0), S.ID)
		AND S.ATIVO = ISNULL(@ATIVO, S.ATIVO)
		AND S.CNPJ = ISNULL(NULLIF(@CNPJ, ''), S.CNPJ)
		AND S.NOME = ISNULL(NULLIF(@NOME, ''), S.NOME)
		AND S.DATA_CRIACAO BETWEEN ISNULL(NULLIF(@DATA_INICIAL, '1900-01-01'), S.DATA_CRIACAO) AND ISNULL(NULLIF(@DATA_FINAL, '1900-01-01'), S.DATA_CRIACAO)
;

SELECT	S.ID AS ID
		, S.NOME AS SEGURADORA
		, dbo.UF_FORMATAR_CPF_CNPJ(S.CNPJ) AS CNPJ
		, S.DATA_CRIACAO AS DATA_CRIACAO
		, S.ATIVO AS ATIVO
		, S.CONTROLA_ANTECIPACAO AS ANTECIPACAO
		, S.DATA_CRIACAO AS DATA_CRIACAO
		, CONVERT(VARCHAR, S.DATA_CRIACAO, 103) AS DATA_ABREVIADA
		, CONVERT(VARCHAR, S.DATA_CRIACAO, 108) AS HORA_ABREVIADA
FROM	#SEGURADORA S
;

DROP TABLE #SEGURADORA;
GO

