
IF OBJECT_ID('UP_SEGURADORA_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_SEGURADORA_BUSCAR;
GO

CREATE PROCEDURE UP_SEGURADORA_BUSCAR (
	@ID INT = NULL
	, @NOME VARCHAR(100) = NULL
	, @CNPJ VARCHAR(14) = NULL
	, @ATIVO BIT = NULL
	, @ANTECIPACAO BIT = NULL
)
AS
SET NOCOUNT ON;

SELECT	*
INTO	#SEGURADORA
FROM	SEGURADORA S
WHERE	S.ID = ISNULL(@ID, S.ID)
		AND S.ATIVO = ISNULL(@ATIVO, S.ATIVO)
		AND S.CNPJ = ISNULL(@CNPJ, S.CNPJ)
		AND S.NOME = ISNULL(@NOME, S.NOME)
		AND S.ANTECIPACAO = ISNULL(@ANTECIPACAO, S.ANTECIPACAO)
;

SELECT	S.ID AS ID
		, S.NOME AS NOME
		, dbo.UF_FORMATAR_CPF_CNPJ(S.CNPJ) AS CNPJ
		, S.ATIVO AS ATIVO
		, S.ANTECIPACAO AS ANTECIPACAO
		, S.DATA_CRIACAO AS DATA_CRIACAO
		, FORMAT(S.DATA_CRIACAO, 'dd/MM/yyyy hh:mm:ss', 'pt-BR') AS DATA_ABREVIADA
FROM	#SEGURADORA S
;

DROP TABLE #SEGURADORA;
GO

