
IF OBJECT_ID('UP_SITUACAO_SINISTRO_CADASTRAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_SITUACAO_SINISTRO_CADASTRAR;
GO

CREATE PROCEDURE UP_SITUACAO_SINISTRO_CADASTRAR (
	@NOME VARCHAR(100)
)
AS
SET NOCOUNT ON;

IF @NOME <> ''
	INSERT INTO SITUACAO_SINISTRO (NOME) SELECT TRIM(@NOME);
GO
