IF OBJECT_ID('fin.UP_SALDO_ATUALIZAR', 'P') IS NOT NULL
	DROP PROCEDURE fin.UP_SALDO_ATUALIZAR;
GO

CREATE PROCEDURE fin.UP_SALDO_ATUALIZAR (
	@LANCAMENTO_ID INT
)
AS
SET NOCOUNT ON;
DECLARE	@CONTA INT, @CATEGORIA INT, @MULTIPLICADOR INT, @VALOR MONEY;

SELECT	@CONTA = L.CONTA_BANCARIA_ID, @CATEGORIA = L.CATEGORIA_ID, @VALOR = L.VALOR
FROM	fin.LANCAMENTO L
WHERE	L.ID = @LANCAMENTO_ID;

SELECT	@MULTIPLICADOR = TL.MULTIPLICADOR FROM fin.CATEGORIA C 
INNER	JOIN fin.TIPO_LANCAMENTO TL
		ON TL.ID = C.TIPO_LANCAMENTO_ID
WHERE C.ID = @CATEGORIA;

UPDATE	fin.CONTA_BANCARIA
SET		SALDO = SALDO + (@VALOR * @MULTIPLICADOR)
WHERE	ID = @CONTA;
GO