
IF OBJECT_ID('UP_SINISTRO_ATUALIZAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_SINISTRO_ATUALIZAR;
GO

CREATE PROCEDURE UP_SINISTRO_ATUALIZAR (
	@ID INT
	, @DATA_RELACAO SMALLDATETIME = NULL
    , @REPRESENTANTE_SEGURADORA_ID INT = NULL
    , @PRAZO_PAGAMENTO SMALLDATETIME = NULL
    , @DATA_OCORRENCIA SMALLDATETIME = NULL
    , @SEGURADO_ID INT = NULL
    , @REFERENCIA VARCHAR(20) = NULL
    , @BILHETE VARCHAR(10) = NULL
    , @VOUCHER VARCHAR(20) = NULL
    , @TIPO_COBERTURA_ID INT = NULL
    , @VALOR_DOLAR MONEY = NULL
    , @VALOR_DOLAR_DESCONTO MONEY = NULL
    , @FEE_DOLAR MONEY = NULL
    , @CAMBIO MONEY = NULL
    , @VALOR_REAL MONEY = NULL
    , @VALOR_REAL_DESCONTO MONEY = NULL
    , @FEE_REAL MONEY = NULL
    , @TRANSFERENCIA_CONTA_INTERNA BIT = NULL
    , @DATA_PAGAMENTO SMALLDATETIME = NULL
    , @DOC_DEVOLVIDO BIT = NULL
    , @DOC_DEVOLVIDO_DESC VARCHAR(4000) = NULL
    , @OBSERVACAO VARCHAR(4000) = NULL
    , @DATA_RECEBIMENTO SMALLDATETIME = NULL
    , @NOTA_DEBITO_ID INT = NULL
    , @TIPO_MOEDA_ID INT = NULL
    , @REMESSA_DOLAR MONEY = NULL
    , @COMISSAO MONEY = NULL
    , @SITUACAO_SINISTRO_ID INT = NULL
    , @SITUACAO_CENTRAL_ID INT = NULL
    , @SITUACAO_SEGURADORA_ID INT = NULL
)
AS
SET NOCOUNT ON;

UPDATE	SINISTRO
SET		DATA_RELACAO = ISNULL(@DATA_RELACAO, DATA_RELACAO)
		, REPRESENTANTE_SEGURADORA_ID = ISNULL(@REPRESENTANTE_SEGURADORA_ID, REPRESENTANTE_SEGURADORA_ID)
		, PRAZO_PAGAMENTO = ISNULL(@PRAZO_PAGAMENTO, PRAZO_PAGAMENTO)
		, DATA_OCORRENCIA = ISNULL(@DATA_OCORRENCIA, DATA_OCORRENCIA)
		, SEGURADO_ID = ISNULL(@SEGURADO_ID, SEGURADO_ID)
		, REFERENCIA = ISNULL(@REFERENCIA, REFERENCIA)
		, BILHETE = ISNULL(@BILHETE, BILHETE)
		, VOUCHER = ISNULL(@VOUCHER, VOUCHER)
		, TIPO_COBERTURA_ID = ISNULL(@TIPO_COBERTURA_ID, TIPO_COBERTURA_ID)
		, VALOR_DOLAR = ISNULL(@VALOR_DOLAR, VALOR_DOLAR)
		, VALOR_DOLAR_DESCONTO = ISNULL(@VALOR_DOLAR_DESCONTO, VALOR_DOLAR_DESCONTO)
		, FEE_DOLAR = ISNULL(@FEE_DOLAR, FEE_DOLAR)
		, CAMBIO = ISNULL(@CAMBIO, CAMBIO)
		, VALOR_REAL = ISNULL(@VALOR_REAL, VALOR_REAL)
		, VALOR_REAL_DESCONTO = ISNULL(@VALOR_REAL_DESCONTO, VALOR_REAL_DESCONTO)
		, FEE_REAL = ISNULL(@FEE_REAL, FEE_REAL)
		, TRANSFERENCIA_CONTA_INTERNA = ISNULL(@TRANSFERENCIA_CONTA_INTERNA, TRANSFERENCIA_CONTA_INTERNA)
		, DATA_PAGAMENTO = ISNULL(@DATA_PAGAMENTO, DATA_PAGAMENTO)
		, DOC_DEVOLVIDO = ISNULL(@DOC_DEVOLVIDO, DOC_DEVOLVIDO)
		, DOC_DEVOLVIDO_DESC = ISNULL(@DOC_DEVOLVIDO_DESC, DOC_DEVOLVIDO_DESC)
		, OBSERVACAO = ISNULL(@OBSERVACAO, OBSERVACAO)
		, DATA_RECEBIMENTO = ISNULL(@DATA_RECEBIMENTO, DATA_RECEBIMENTO)
		, NOTA_DEBITO_ID = ISNULL(@NOTA_DEBITO_ID, NOTA_DEBITO_ID)
		, TIPO_MOEDA_ID = ISNULL(@TIPO_MOEDA_ID, TIPO_MOEDA_ID)
		, REMESSA_DOLAR = ISNULL(@REMESSA_DOLAR, REMESSA_DOLAR)
		, COMISSAO = ISNULL(@COMISSAO, COMISSAO)
		, SITUACAO_SINISTRO_ID = ISNULL(@SITUACAO_SINISTRO_ID, SITUACAO_SINISTRO_ID)
WHERE	ID = @ID
;
GO
