
IF OBJECT_ID('UP_TIPO_MOEDA_CADASTRAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_TIPO_MOEDA_CADASTRAR;
GO

CREATE PROCEDURE UP_TIPO_MOEDA_CADASTRAR (
	@NOME VARCHAR(100)
	, @ABREVIACAO VARCHAR(5) = NULL
)
AS
SET NOCOUNT ON;

IF	@NOME <> ''
BEGIN
	INSERT	INTO TIPO_MOEDA (NOME, NOME_ABREVIADO)
	SELECT	@NOME, @ABREVIACAO;
END
GO
