
IF OBJECT_ID('UP_TIPO_COBERTURA_DELETAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_TIPO_COBERTURA_DELETAR;
GO

CREATE PROCEDURE UP_TIPO_COBERTURA_DELETAR (
	@ID INT
)
AS
SET NOCOUNT ON;

UPDATE TIPO_COBERTURA SET ATIVO = 0 WHERE ID = @ID;
GO
