
IF OBJECT_ID('UP_TIPO_LANCAMENTO_CADASTRAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_TIPO_LANCAMENTO_CADASTRAR;
GO

CREATE PROCEDURE UP_TIPO_LANCAMENTO_CADASTRAR (
	@NOME VARCHAR(50)
	, @MULTIPLICADOR TINYINT = 1
)
AS
SET NOCOUNT ON;

IF ISNULL(@NOME, '') <> ''
	INSERT INTO TIPO_LANCAMENTO (NOME, MULTIPLICADOR) SELECT TRIM(@NOME), ISNULL(@MULTIPLICADOR, 1);
GO
