
IF OBJECT_ID('UP_TIPO_LANCAMENTO_DELETAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_TIPO_LANCAMENTO_DELETAR;
GO

CREATE PROCEDURE UP_TIPO_LANCAMENTO_DELETAR (
	@ID INT
)
AS
SET NOCOUNT ON;

UPDATE TIPO_LANCAMENTO SET ATIVO = 0 WHERE ID = @ID;
GO
