
IF OBJECT_ID('UP_TIPO_COBERTURA_ATUALIZAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_TIPO_COBERTURA_ATUALIZAR;
GO

CREATE PROCEDURE UP_TIPO_COBERTURA_ATUALIZAR (
	@ID INT
	, @NOME VARCHAR(100) = NULL
	, @GRUPO VARCHAR(100) = NULL
)
AS
SET NOCOUNT ON;

UPDATE	TIPO_COBERTURA
SET		NOME = ISNULL(NULLIF(@NOME, ''), NOME)
		, GRUPO = ISNULL(NULLIF(@GRUPO, ''), GRUPO)
WHERE	ID = @ID
;
GO
