
IF OBJECT_ID('UP_TIPO_MOEDA_DELETAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_TIPO_MOEDA_DELETAR;
GO

CREATE PROCEDURE UP_TIPO_MOEDA_DELETAR (
	@ID INT = NULL
)
AS
SET NOCOUNT ON;

UPDATE TIPO_MOEDA SET ATIVO = 0 WHERE ID = @ID
;
GO
