
IF OBJECT_ID('UP_TIPO_MOEDA_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE UP_TIPO_MOEDA_BUSCAR;
GO

CREATE PROCEDURE UP_TIPO_MOEDA_BUSCAR (
	@ID INT = NULL
	, @NOME VARCHAR(100) = NULL
	, @ABREVIACAO VARCHAR(5) = NULL
	, @ATIVO BIT = 1
)
AS
SET NOCOUNT ON;

SELECT	TM.ID AS ID
		, TM.NOME AS NOME
		, ISNULL(TM.NOME_ABREVIADO, '') AS ABREVIACAO
		, TM.ATIVO AS ATIVO
FROM	TIPO_MOEDA TM
WHERE	TM.ID = ISNULL(NULLIF(@ID, 0), TM.ID)
		AND TM.ATIVO = ISNULL(@ATIVO, TM.ATIVO)
		AND NOME_ABREVIADO = ISNULL(NULLIF(@ABREVIACAO, ''), TM.NOME_ABREVIADO)
		AND NOME = ISNULL(NULLIF(@NOME, ''), TM.NOME)
;
GO
