
IF OBJECT_ID('fin.UP_TIPO_LANCAMENTO_BUSCAR', 'P') IS NOT NULL
	DROP PROCEDURE fin.UP_TIPO_LANCAMENTO_BUSCAR;
GO

CREATE PROCEDURE fin.UP_TIPO_LANCAMENTO_BUSCAR (
	@ID INT = NULL
	, @NOME VARCHAR(50) = NULL
	, @ATIVO BIT = 1
	, @MULTIPLICADOR INT = NULL
)
AS
SET NOCOUNT ON;

SELECT	TL.ID AS ID
		, TL.NOME AS NOME
		, TL.ATIVO AS ATIVO
		, TL.MULTIPLICADOR AS MULTIPLICADOR
FROM	fin.TIPO_LANCAMENTO TL
WHERE	TL.ID = ISNULL(@ID, TL.ID)
		AND TL.ATIVO = ISNULL(@ATIVO, TL.ATIVO)
		AND TL.NOME = ISNULL(@NOME, TL.NOME)
		AND TL.MULTIPLICADOR = ISNULL(@MULTIPLICADOR, TL.MULTIPLICADOR)
;
GO
