IF OBJECT_ID('UF_FORMATAR_CPF_CNPJ', 'FN') IS NOT NULL
	DROP FUNCTION UF_FORMATAR_CPF_CNPJ;
GO

CREATE FUNCTION UF_FORMATAR_CPF_CNPJ (@CAMPO VARCHAR(14))
RETURNS VARCHAR(18)
AS
BEGIN
	DECLARE @RETORNO VARCHAR(18);
	
	--CPF
	IF LEN(@CAMPO) = 11
		SET @RETORNO = CONCAT(SUBSTRING(@CAMPO, 1, 3), '.', SUBSTRING(@CAMPO, 4, 3), '.', SUBSTRING(@CAMPO, 7, 3), '-', SUBSTRING(@CAMPO, 10, 2));
	--CNPJ
	ELSE IF LEN(@CAMPO) = 14
		SET @RETORNO = CONCAT(SUBSTRING(@CAMPO, 1, 2), '.', SUBSTRING(@CAMPO, 3, 3), '.', SUBSTRING(@CAMPO, 6, 3), '/', SUBSTRING(@CAMPO, 9, 4), '-', SUBSTRING(@CAMPO, 13, 2));
	--Não identificado
	ELSE
		SET @RETORNO = @CAMPO;
	RETURN @RETORNO;
END
GO