IF OBJECT_ID('UF_TAMANHO_CPF_CNPJ', 'FN') IS NOT NULL
	DROP FUNCTION UF_TAMANHO_CPF_CNPJ;
GO

CREATE FUNCTION UF_TAMANHO_CPF_CNPJ (@CAMPO VARCHAR(14))
RETURNS VARCHAR(14)
AS
BEGIN
	DECLARE @RETORNO VARCHAR(14);
	
	IF LEN(ISNULL(@CAMPO, '')) = 0
		SET @RETORNO = @CAMPO;
	--CNPJ
	ELSE IF LEN(@CAMPO) > 11
		SET @RETORNO = RIGHT(CONCAT('00000000000000', NULLIF(@CAMPO, '')), 14);
	--CPF
	ELSE
		SET @RETORNO = RIGHT(CONCAT('00000000000', NULLIF(@CAMPO, '')), 11);

	RETURN @RETORNO;
END
GO