
IF OBJECT_ID('CAP_CONTA', 'U') IS NULL
	CREATE TABLE CAP_CONTA (
		ID INT IDENTITY(1,1) NOT NULL
		, NOME VARCHAR(100) NOT NULL
		, ATIVO BIT NOT NULL DEFAULT 1
		, BANCO VARCHAR(100) NULL
		, AGENCIA VARCHAR(4) NULL
		, DIGITO_AGENCIA CHAR NULL
		, CONTA VARCHAR(10) NULL
		, DIGITO_CONTA CHAR NULL
		, SALDO MONEY NULL
		, CONSTRAINT PK_CAP_CONTA_ID PRIMARY KEY CLUSTERED (ID)
	);
GO
