
IF OBJECT_ID('CAP_CLIENTE', 'U') IS NULL
	CREATE TABLE CAP_CLIENTE (
		ID INT IDENTITY(1,1) NOT NULL
		, NOME VARCHAR(100) NOT NULL
		, ATIVO BIT NOT NULL DEFAULT 1
		, SEGURADORA_ID INT NULL
		, CONSTRAINT PK_CAP_CLIENTE_ID PRIMARY KEY CLUSTERED (ID)
	);
GO
