
IF OBJECT_ID('fin.CATEGORIA', 'U') IS NULL
	CREATE TABLE fin.CATEGORIA (
		ID INT IDENTITY(1,1) NOT NULL
		, NOME VARCHAR(100) NOT NULL
		, ATIVO BIT NOT NULL DEFAULT 1
		, TIPO_LANCAMENTO_ID INT NOT NULL
		, CONSTRAINT PK_CATEGORIA_ID PRIMARY KEY CLUSTERED (ID)
		--, CONSTRAINT FK_CATEGORIA_TIPO_LANCAMENTO_ID FOREIGN KEY (TIPO_LANCAMENTO_ID) REFERENCES TIPO_LANCAMENTO (ID)
	);
GO
