
IF OBJECT_ID('fin.CLIENTE', 'U') IS NULL
	CREATE TABLE fin.CLIENTE (
		ID INT IDENTITY(1,1) NOT NULL
		, NOME VARCHAR(100) NOT NULL
		, NUM_DOCUMENTO VARCHAR(14) NULL
		, ATIVO BIT NOT NULL DEFAULT 1
		, SEGURADORA_ID INT NULL
		, CONSTRAINT PK_CLIENTE_ID PRIMARY KEY CLUSTERED (ID)
	);
GO
