
IF OBJECT_ID('fin.FECHAMENTO', 'U') IS NULL
	CREATE TABLE fin.FECHAMENTO (
		ID INT IDENTITY(1,1) NOT NULL
		, DATA_FECHAMENTO SMALLDATETIME NULL
		, REMESSA BIT NULL
		, DOLAR_REMESSA MONEY NULL
		, EMISSOR_ID INT NULL
		, CONSTRAINT PK_FECHAMENTO_ID PRIMARY KEY CLUSTERED (ID)
	);
GO
