
IF OBJECT_ID('FECHAMENTO', 'U') IS NULL
	CREATE TABLE FECHAMENTO (
		ID INT IDENTITY(1,1) NOT NULL
		, ATIVO BIT DEFAULT 1 NOT NULL
		, DATA_FECHAMENTO SMALLDATETIME NULL
		, REMESSA BIT NULL
	);
GO
