
IF OBJECT_ID('fin.FORNECEDOR', 'U') IS NULL
	CREATE TABLE fin.FORNECEDOR (
		ID INT IDENTITY(1,1) NOT NULL
		, NOME VARCHAR(100) NOT NULL
		, CNPJ VARCHAR(14) NULL
		, ATIVO BIT NOT NULL DEFAULT 1
		, CONSTRAINT PK_FORNECEDOR_ID PRIMARY KEY CLUSTERED (ID)
	);
GO
