
IF OBJECT_ID('imp.IMPORTACAO', 'U') IS NULL
	CREATE TABLE imp.IMPORTACAO (
		ID INT IDENTITY(1,1) NOT NULL
		, SEGURADORA_ID INT NOT NULL
		, ANTECIPACAO BIT DEFAULT 0 NOT NULL
		, NOME_ARQUIVO VARCHAR(300) NULL
		, CAMINHO_ARQUIVO NVARCHAR(MAX) NULL
		, BIT_PROCESSADA BIT NOT NULL DEFAULT 0
		, ATIVO BIT DEFAULT 1 NOT NULL
		, DATA_CADASTRO SMALLDATETIME NOT NULL DEFAULT GETDATE()
		, CONSTRAINT PK_IMPORTACAO_ID PRIMARY KEY CLUSTERED (ID)
		--, CONSTRAINT FK_IMPORTACAO_SEGURADORA_ID FOREIGN KEY (SEGURADORA_ID) REFERENCES SEGURADORA (ID)
	);
GO