
IF OBJECT_ID('LANCAMENTO', 'U') IS NULL
	CREATE TABLE LANCAMENTO (
		ID INT IDENTITY(1,1) NOT NULL
		, DESCRICAO VARCHAR(300) NULL
		, ATIVO BIT NOT NULL DEFAULT 1
		, FORNCEDOR_ID INT NOT NULL
		, CATEGORIA_ID INT NOT NULL
		, CENTRO_CUSTO_ID INT NOT NULL
		, CUSTO_FIXO BIT NOT NULL
		, VALOR MONEY NOT NULL
		, DATA_LANCAMENTO SMALLDATETIME NOT NULL
		, CONSTRAINT PK_LANCAMENTO_ID PRIMARY KEY CLUSTERED (ID)
	);
GO
