
IF OBJECT_ID('fin.LANCAMENTO', 'U') IS NULL
	CREATE TABLE fin.LANCAMENTO (
		ID INT IDENTITY(1,1) NOT NULL
		, DESCRICAO VARCHAR(300) NULL
		, ATIVO BIT NOT NULL DEFAULT 1
		, CUSTO_FIXO BIT NOT NULL
		, VALOR MONEY NOT NULL
		, DATA_LANCAMENTO SMALLDATETIME NULL
		, FECHAMENTO_ID INT NULL
		, CLIENTE_ID INT NOT NULL
		, CONTA_BANCARIA_ID INT NOT NULL
		, CENTRO_CUSTO_ID INT NOT NULL
		, CATEGORIA_ID INT NOT NULL
		, FORNECEDOR_ID INT NOT NULL
		, CONSTRAINT PK_LANCAMENTO_ID PRIMARY KEY CLUSTERED (ID)
	);
GO
