
IF OBJECT_ID('PATROCINIO', 'U') IS NULL
CREATE TABLE PATROCINIO (
    ID INT IDENTITY(1,1) NOT NULL
	, SEGURADORA_ID INT NOT NULL
    , REPRESENTANTE_ID INT NOT NULL
	, CONSTRAINT PK_PATROCINIO_ID PRIMARY KEY CLUSTERED (ID)
	, CONSTRAINT FK_SEGURADORA_ID FOREIGN KEY (SEGURADORA_ID) REFERENCES SEGURADORA (ID)
	, CONSTRAINT FK_REPRESENTANTE_ID FOREIGN KEY (REPRESENTANTE_ID) REFERENCES REPRESENTANTE (ID)
);
GO
