
IF OBJECT_ID('imp.REGISTRO', 'U') IS NULL
	CREATE TABLE imp.REGISTRO (
		ID INT IDENTITY(1,1) NOT NULL
		, IMPORTACAO_ID INT NOT NULL
		, NUMERO_SINISTRO VARCHAR(25) NULL
		, CIA VARCHAR(50) NULL
		, PROCESSO VARCHAR(50) NULL
		, BILHETE VARCHAR(25) NULL
		, DATA_EMISSAO_VOUCHER DATE NULL
		, REFERENCIA VARCHAR(20) NULL
		, DATA_ATENDIMENTO DATE NULL
		, DATA_OCORRENCIA DATE NULL
		, NOME_SEGURADO VARCHAR(100) NULL
		, DOCUMENTO VARCHAR(14) NULL
		, VOUCHER VARCHAR(50) NULL
		, COBERTURA_RECLAMADA VARCHAR(200) NULL
		, NOME_BANCO VARCHAR(100) NULL
		, NUMERO_AGENCIA VARCHAR(4) NULL
		, DIGITO_AGENCIA VARCHAR(1) NULL
		, NUMERO_CONTA VARCHAR(10) NULL
		, DIGITO_CONTA VARCHAR(1) NULL
		, EMAIL_CONTATO VARCHAR(100) NULL
		, CUSTO_ORIGINAL MONEY NULL
		, TIPO_MOEDA VARCHAR(3) NULL
		, VALOR_FINAL MONEY NULL
		, FEE MONEY NULL
		, TIPO_MOEDA_FEE VARCHAR(3) NULL
		, VALOR_ND_US MONEY NULL
		, VALOR_ND_RS MONEY NULL
		, TAXA_CAMBIO FLOAT NULL
		, NOTA_DEBITO VARCHAR(20) NULL
		, DATA_EMISSAO_ND SMALLDATETIME NULL
		, DATA_ENVIO SMALLDATETIME NULL
		, STATUS_PAGAMENTO VARCHAR(20) NULL
		, SINISTRO_ID INT NULL
		, CONSTRAINT PK_REGISTRO_ID PRIMARY KEY CLUSTERED (ID)
	);
GO