
IF OBJECT_ID('REPRESENTANTE', 'U') IS NULL
	CREATE TABLE REPRESENTANTE (
		REPRESENTANTE_ID INT IDENTITY (1, 1) PRIMARY KEY
		, NOME VARCHAR(100)
		, CNPJ VARCHAR(14)
		, BIT_ATIVO BIT DEFAULT 1 NOT NULL
		, DATA_CRIACAO SMALLDATETIME DEFAULT GETDATE() NOT NULL
	);
GO
