
IF OBJECT_ID('REPRESENTANTE', 'U') IS NULL
	CREATE TABLE REPRESENTANTE (
		ID INT IDENTITY (1,1) NOT NULL
		, NOME VARCHAR(100) NOT NULL
		, CNPJ VARCHAR(14) NOT NULL
		, ATIVO BIT DEFAULT 1 NOT NULL
		, DATA_CRIACAO SMALLDATETIME DEFAULT GETDATE() NOT NULL
		, CONSTRAINT PK_REPRESENTANTE_ID PRIMARY KEY CLUSTERED (ID)
	);
GO

--DROP TABLE REPRESENTANTE