use develop
GO

IF OBJECT_ID('SEGURADORA', 'U') IS NULL
CREATE TABLE SEGURADORA (
    SEGURADORA_ID INT IDENTITY(1,1) PRIMARY KEY
    , NOME VARCHAR(100) NOT NULL
    , CNPJ VARCHAR(14) NOT NULL
    , SITUACAO_SISTEMA_ID INT NOT NULL
    , DATA_CRIACAO SMALLDATETIME DEFAULT GETDATE()
    , USER_CRIACAO INT
);
GO