
IF OBJECT_ID('SEGURADORA', 'U') IS NULL
CREATE TABLE SEGURADORA (
    ID INT IDENTITY(1,1) PRIMARY KEY
    , NOME VARCHAR(100) NOT NULL
    , CNPJ VARCHAR(14) NOT NULL
	, CONTROLA_ANTECIPACAO BIT NOT NULL
    , ATIVO BIT NOT NULL
    , DATA_CRIACAO SMALLDATETIME DEFAULT GETDATE()
);
GO

--DROP TABLE SEGURADORA