
IF OBJECT_ID('SEGURADO', 'U') IS NULL
	CREATE TABLE SEGURADO (
		ID INT IDENTITY(1,1) NOT NULL
		, NOME VARCHAR(100) NOT NULL
		, CPF VARCHAR(14) NULL
		, BANCO VARCHAR(100) NULL
		, AGENCIA VARCHAR(4) NULL
		, DIGITO_AGENCIA CHAR NULL
		, CONTA VARCHAR(10) NULL
		, DIGITO_CONTA CHAR NULL
		, BENEFICIARIO VARCHAR(100) NULL
		, CPF_BENEFICIARIO VARCHAR(14) NULL
		, EMAIL VARCHAR(100) NULL
		, CONTA_CADASTRADA BIT NULL
		, ATIVO BIT NOT NULL DEFAULT 1
		, CONSTRAINT PK_SEGURADO_ID PRIMARY KEY CLUSTERED (ID)
	);
GO
