
IF OBJECT_ID('SEGURADORA', 'U') IS NULL
CREATE TABLE SEGURADORA (
    ID INT IDENTITY(1,1) NOT NULL
    , NOME VARCHAR(100) NOT NULL
    , CNPJ VARCHAR(14) NOT NULL
	, CONTROLA_ANTECIPACAO BIT NOT NULL
    , ATIVO BIT NOT NULL
    , DATA_CRIACAO SMALLDATETIME DEFAULT GETDATE()
	, CONSTRAINT PK_SEGURADORA_ID PRIMARY KEY CLUSTERED (ID)
);
GO

--DROP TABLE SEGURADORA