
IF OBJECT_ID('SINISTRO', 'U') IS NULL
	CREATE TABLE SINISTRO (
		ID INT IDENTITY(1,1) NOT NULL
		, ATIVO BIT NOT NULL DEFAULT 1
		, DATA_RELACAO SMALLDATETIME NULL
		, REPRESENTANTE_SEGURADORA_ID INT NOT NULL
		, PRAZO_PAGAMENTO SMALLDATETIME NULL
		, DATA_OCORRENCIA SMALLDATETIME NULL
		, SEGURADO_ID INT NOT NULL
		, REFERENCIA VARCHAR(20) NOT NULL
		, BILHETE VARCHAR(10) NULL
		, VOUCHER VARCHAR(20) NULL
		, TIPO_COBERTURA_ID INT NOT NULL
		, VALOR_DOLAR MONEY NULL
		, VALOR_DOLAR_DESCONTO MONEY NULL
		, FEE_DOLAR MONEY NULL
		, CAMBIO MONEY NULL
		, VALOR_REAL MONEY NULL
		, VALOR_REAL_DESCONTO MONEY NULL
		, FEE_REAL MONEY NULL
		, TRANSFERENCIA_CONTA_INTERNA BIT NULL DEFAULT 0
		, DATA_PAGAMENTO SMALLDATETIME NULL
		, DOC_DEVOLVIDO BIT NULL
		, DOC_DEVOLVIDO_DESC VARCHAR(4000) NULL
		, OBSERVACAO VARCHAR(4000) NULL
		, DATA_RECEBIMENTO SMALLDATETIME NULL
		, NOTA_DEBITO_ID INT NOT NULL
		, TIPO_MOEDA_ID INT NOT NULL
		, REMESSA_DOLAR MONEY NULL
		, COMISSAO MONEY NULL
		, SITUACAO_SINISTRO_ID INT NOT NULL
		, DATA_CRIACAO SMALLDATETIME DEFAULT GETDATE()
		, CONSTRAINT PK_SINISTRO_ID PRIMARY KEY CLUSTERED (ID)
	);
GO
