IF OBJECT_ID('SINISTRO', 'U') IS NULL
	CREATE TABLE SINISTRO (
		ID INT IDENTITY(1,1) NOT NULL
		, NUMERO_SINISTRO VARCHAR(25) NULL
		, PROCESSO VARCHAR(50) NULL
		, BILHETE VARCHAR(25) NULL
		, REFERENCIA VARCHAR(20) NULL
		, DATA_ATENDIMENTO DATE NULL
		, DATA_OCORRENCIA DATE NULL
		, VOUCHER VARCHAR(50) NULL
		, COBERTURA VARCHAR(200) NULL
		, CUSTO_ORIGINAL MONEY NULL
		, TIPO_MOEDA VARCHAR(3) NULL
		, VALOR_FINAL MONEY NULL
		, FEE MONEY NULL
		, TIPO_MOEDA_FEE VARCHAR(3) NULL
		, VALOR_DOLAR MONEY NULL
		, VALOR_REAL MONEY NULL
		, DOLAR FLOAT NULL
		, REGISTRO_ID INT NULL
		, NOTA_DEBITO_ID INT NULL
		, SEGURADO_ID INT NULL
		, PATROCINIO_ID INT NULL
		, CONSTRAINT PK_SINISTRO_ID PRIMARY KEY CLUSTERED (ID)
	);
GO