
IF OBJECT_ID('fin.TIPO_LANCAMENTO', 'U') IS NULL
	CREATE TABLE fin.TIPO_LANCAMENTO (
		ID INT IDENTITY(1,1) NOT NULL
		, NOME VARCHAR(50) NOT NULL
		, ATIVO BIT DEFAULT 1 NOT NULL
		, MULTIPLICADOR INT DEFAULT 1 NOT NULL
		, CONSTRAINT PK_TIPO_LANCAMENTO_ID PRIMARY KEY CLUSTERED (ID)
	);
GO
