
IF OBJECT_ID('TIPO_COBERTURA', 'U') IS NULL
	CREATE TABLE TIPO_COBERTURA (
		ID INT IDENTITY(1,1) NOT NULL
		, NOME VARCHAR(100) NOT NULL
		, GRUPO VARCHAR(100) NOT NULL
		, ATIVO BIT NOT NULL DEFAULT 1
		, CONSTRAINT PK_TIPO_COBERTURA_ID PRIMARY KEY CLUSTERED (ID)
	);
GO
