
IF OBJECT_ID('TIPO_MOEDA', 'U') IS NULL
	CREATE TABLE TIPO_MOEDA (
		ID INT IDENTITY(1,1) NOT NULL
		, NOME VARCHAR(20) NOT NULL
		, NOME_ABREVIADO VARCHAR(5) NULL
		, ATIVO BIT NOT NULL DEFAULT 1
		, CONSTRAINT PK_TIPO_MOEDA PRIMARY KEY (ID)
	);
GO
