CREATE TABLE SINISTRO (
    SINISTRO_ID INT IDENTITY(1,1)
    , DATA_RELACAO SMALLDATETIME --REF_RELACAO
    , COMPANHIA_REPRESENTANTE_SEGURADORA_ID INT
    , PRAZO_PAGAMENTO SMALLDATETIME
    , DATA_OCORRENCIA SMALLDATETIME
    , SEGURADO_ID INT
    , REFERENCIA VARCHAR(20)
    , BILHETE VARCHAR(10)
    , VOUCHER VARCHAR(20)
    , TIPO_COBERTURA_ID INT
    , VALOR_DOLAR MONEY
    , VALOR_DOLAR_DESCONTO MONEY
    , FEES_DOLAR MONEY
    --, CAMBIO MONEY
    , VALOR_REAL MONEY
    , VALOR_REAL_DESCONTO MONEY
    --, FEES_REAL MONEY
    , TRANSFERENCIA_CONTA_INTERNA BIT
    , DATA_PAGAMENTO SMALLDATETIME
    , DOC_DEVOLVIDO BIT
    , DOC_DEVOLVIDO_DESC VARCHAR(4000)
    , OBSERVACAO VARCHAR(4000)
    , DATA_RECEBIMENTO SMALLDATETIME
    , NOTA_DEBITO_ID INT
    , TIPO_MOEDA_ID INT
    , REMESSA_DOLAR MONEY
    , COMISSAO MONEY
    , SITUACAO_SINISTRO_ID INT
    , SITUACAO_CENTRAL_ID INT
    , SITUACAO_SEGURADORA_ID INT
    , DATA_CRIACAO SMALLDATETIME DEFAULT GETDATE()
);
GO

CREATE TABLE NOTA_DEBITO (
    NOTA_DEBITO INT IDENTITY(1,1)
    , NOTA VARCHAR(20)
    , DATA_EMISSAO SMALLDATETIME
    --, SEGURADORA_ID INT
    , DATA_ENVIO SMALLDATETIME
    , PREVISAO_PAGAMENTO SMALLDATETIME
    , DATA_PAGAMENTO SMALLDATETIME
    , OBSERVACAO VARCHAR(4000)
    , DATA_REPASSE_REMESSA SMALLDATETIME
    , DATA_EMAIL SMALLDATETIME
    , EMISSOR_ID INT
    , DOLAR_BANCO_CENTRAL MONEY
    --, U$ MONEY
    --, SALDO_REMESSA MONEY
    --, SPREAD_REMESSA REAL
    --, SPREAD_ND REAL
    --, DOLAR_BC_ND MONEY
    --, DIFF_ND_BC_ND_WTA MONEY
    --, SPREAD_ND_WTA_BC REAL
    --, DOLAR_ND_CC MONEY
    --, DIFF_ND_CC_ND_WTA MONEY
    --, SPREAD_ND_WTA_CC REAL
    --, NF BIT
    , 
);
GO

CREATE TABLE REGISTRO_IMPORTACAO_NOTA_DEBITO (
    REGISTRO_IMPORTACAO_NOTA_DEBITO_ID INT IDENTITY(1,1)
);
GO


CREATE TABLE SITUACAO_CENTRAL (
    SITUACAO_CENTRAL_ID INT IDENTITY(1,1)
    , NOME VARCHAR(100)
    , SITUACAO_SISTEMA_ID INT
);
GO

CREATE TABLE SITUACAO_SEGURADORA (
    SITUACAO_SEGURADORA_ID INT IDENTITY(1,1)
    , NOME VARCHAR(100)
    , SITUACAO_SISTEMA_ID INT
);
GO
